export const DATA_PAYMENT = {
    "status": true,
    "data": {
        "CC": {
            "amex debit card": {
                "id": 9,
                "name": "amex debit card",
                "code": "AMEX",
                "enable": true,
                "platformCode": null,
                "mode": "CC",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "ccnum": true,
                    "ccexpmon": true,
                    "ccvv": true,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "ccexpyr": true,
                    "state": false,
                    "productinfo": true,
                    "ccname": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "dinersclub debit card": {
                "id": 10,
                "name": "dinersclub debit card",
                "code": "DINR",
                "enable": true,
                "platformCode": null,
                "mode": "CC",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "ccnum": true,
                    "ccexpmon": true,
                    "ccvv": true,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "ccexpyr": true,
                    "state": false,
                    "productinfo": true,
                    "ccname": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            }
        },
        "NEFT": {
            "neft": {
                "id": 4,
                "name": "neft",
                "code": "NEFT",
                "enable": true,
                "platformCode": null,
                "mode": "NEFT",
                "attributeNames": {},
                "attributeValueMap": {}
            }
        },
        "NB": {
            "emi": {
                "id": 14,
                "name": "emi",
                "code": "EMI",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "bank of maharashtra  ": {
                "id": 16,
                "name": "bank of maharashtra  ",
                "code": "BOMB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "development credit bank ": {
                "id": 19,
                "name": "development credit bank ",
                "code": "DCBB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "corporation bank": {
                "id": 18,
                "name": "corporation bank",
                "code": "CRPB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "jammu and kashmir bank": {
                "id": 26,
                "name": "jammu and kashmir bank",
                "code": "JAKB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "cityunion": {
                "id": 38,
                "name": "cityunion",
                "code": "CUBB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "kotak bank": {
                "id": 43,
                "name": "kotak bank",
                "code": "162B",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "state bank of patiala": {
                "id": 40,
                "name": "state bank of patiala",
                "code": "SBPB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "south indian bank": {
                "id": 33,
                "name": "south indian bank",
                "code": "SOIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "indusind bank": {
                "id": 24,
                "name": "indusind bank",
                "code": "INIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "icici bank netbanking": {
                "id": 11,
                "name": "icici bank netbanking",
                "code": "ICIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "cash on delivery": {
                "id": 13,
                "name": "cash on delivery",
                "code": "COD",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "bank of india  ": {
                "id": 15,
                "name": "bank of india  ",
                "code": "BOIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "vijaya bank": {
                "id": 36,
                "name": "vijaya bank",
                "code": "VJYB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "dcb bank - corporate netbanking": {
                "id": 45,
                "name": "dcb bank - corporate netbanking",
                "code": "DCBCORP",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "state bank of bikaner and jaipur": {
                "id": 29,
                "name": "state bank of bikaner and jaipur",
                "code": "SBBJB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "sbi bank netbanking": {
                "id": 12,
                "name": "sbi bank netbanking",
                "code": "SBIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "federal bank ": {
                "id": 20,
                "name": "federal bank ",
                "code": "FEDB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "karur vysya": {
                "id": 28,
                "name": "karur vysya",
                "code": "KRVB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "karnataka bank": {
                "id": 27,
                "name": "karnataka bank",
                "code": "KRKB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "punjab national bank": {
                "id": 46,
                "name": "punjab national bank",
                "code": "PNBB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "dena bank": {
                "id": 21,
                "name": "dena bank",
                "code": "DENN",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "indian overseas bank": {
                "id": 25,
                "name": "indian overseas bank",
                "code": "INOB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "canara bank": {
                "id": 39,
                "name": "canara bank",
                "code": "CABB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "state bank of hyderabad": {
                "id": 30,
                "name": "state bank of hyderabad",
                "code": "SBHB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "yes bank": {
                "id": 37,
                "name": "yes bank",
                "code": "YESB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "catholic syrian bank": {
                "id": 44,
                "name": "catholic syrian bank",
                "code": "CSBN",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "saraswat bank": {
                "id": 47,
                "name": "saraswat bank",
                "code": "SRSWT",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "central bank of india  ": {
                "id": 17,
                "name": "central bank of india  ",
                "code": "CBIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "union bank of india": {
                "id": 34,
                "name": "union bank of india",
                "code": "UBIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "citi bank netbanking": {
                "id": 41,
                "name": "citi bank netbanking",
                "code": "CITNB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "union bank - corporate netbanking": {
                "id": 48,
                "name": "union bank - corporate netbanking",
                "code": "UBIBC",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "indian bank": {
                "id": 23,
                "name": "indian bank",
                "code": "INDB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "state bank of travancore": {
                "id": 32,
                "name": "state bank of travancore",
                "code": "SBTB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "united bank of india": {
                "id": 35,
                "name": "united bank of india",
                "code": "UNIB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "hdfc netbanking": {
                "id": 5,
                "name": "hdfc netbanking",
                "code": "HDFC",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "industrial development bank of india": {
                "id": 22,
                "name": "industrial development bank of india",
                "code": "IDBB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "axis bank netbanking": {
                "id": 3,
                "name": "axis bank netbanking",
                "code": "AXISB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "ing vysya bank": {
                "id": 50,
                "name": "ing vysya bank",
                "code": "INGB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "deutsche bank": {
                "id": 42,
                "name": "deutsche bank",
                "code": "DSHB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "punjab national bank-corporate": {
                "id": 49,
                "name": "punjab national bank-corporate",
                "code": "CPNB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "state bank of mysore": {
                "id": 31,
                "name": "state bank of mysore",
                "code": "SBMB",
                "enable": true,
                "platformCode": null,
                "mode": "NB",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            }
        },
        "WALLET": {
            "paytm": {
                "id": 53,
                "name": "paytm",
                "code": "PAYTM",
                "enable": true,
                "platformCode": null,
                "mode": "WALLET",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "payumoney": {
                "id": 51,
                "name": "payumoney",
                "code": "PAYUMONEY",
                "enable": true,
                "platformCode": null,
                "mode": "WALLET",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "mobikwik": {
                "id": 52,
                "name": "mobikwik",
                "code": "MOBIKWIK",
                "enable": true,
                "platformCode": null,
                "mode": "WALLET",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "state": false,
                    "productinfo": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            }
        },
        "DC": {
            "visa debit card": {
                "id": 2,
                "name": "visa debit card",
                "code": "VISA",
                "enable": true,
                "platformCode": null,
                "mode": "DC",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "ccnum": true,
                    "ccexpmon": true,
                    "ccvv": true,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "ccexpyr": true,
                    "state": false,
                    "productinfo": true,
                    "ccname": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "maestro debit card": {
                "id": 7,
                "name": "maestro debit card",
                "code": "SMAE",
                "enable": true,
                "platformCode": null,
                "mode": "DC",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "ccnum": true,
                    "ccexpmon": true,
                    "ccvv": true,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "ccexpyr": true,
                    "state": false,
                    "productinfo": true,
                    "ccname": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            },
            "mastercard debit card": {
                "id": 8,
                "name": "mastercard debit card",
                "code": "MAST",
                "enable": true,
                "platformCode": null,
                "mode": "DC",
                "attributeNames": {
                    "country": false,
                    "firstname": true,
                    "address2": false,
                    "city": false,
                    "address1": false,
                    "ccnum": true,
                    "ccexpmon": true,
                    "ccvv": true,
                    "lastname": false,
                    "zipcode": false,
                    "phone": true,
                    "additional_charges": false,
                    "ccexpyr": true,
                    "state": false,
                    "productinfo": true,
                    "ccname": true,
                    "email": true,
                    "bankcode": true
                },
                "attributeValueMap": {}
            }
        }
    }
};