export const DATA_S = {
    "cart": {
        "id": 1,
        "cartRefId": "test",
        "sessionId": "WYzteVSLGxsMG0jbp6QqA1GKRhITK7Sk",
        "userId": "uioy",
        "isPersistant": true,
        "createdAt": 1493279962000,
        "updatedAt": 1493974364000,
        "closedAt": 946668601000,
        "orderId": "ygg",
        "totalAmount": 4.4,
        "totalOffer": 27.73,
        "totalAmountWithOffer": 52.2,
        "taxes": 234.2,
        "totalAmountWithTaxes": 24.1,
        "shippingCharges": 43.2,
        "currency": "fddd",
        "isGift": false,
        "giftMessage": "kjjk",
        "giftPackingCharges": 23.2,
        "totalPayableAmount": 23.2
    },
    "itemsList": [
        {
            "id": 1,
            "cartId": 1,
            "productId": "msn2vz8r1blt1p",
            "createdAt": 1493794107000,
            "updatedAt": 1493794107000,
            "amount": 7,
            "offer": 7,
            "amountWithOffer": 79,
            "taxes": 7,
            "amountWithTaxes": 7,
            "totalPayableAmount": 7,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": true,
            "productQuantity": 8,
            "productUnitPrice": 8,
            "expireAt": 946668601000
        },
        {
            "id": 2,
            "cartId": 1,
            "productId": "jknnnj",
            "createdAt": 1493794140000,
            "updatedAt": 1493794140000,
            "amount": 4,
            "offer": 4,
            "amountWithOffer": 4,
            "taxes": 4,
            "amountWithTaxes": 4,
            "totalPayableAmount": 4,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": false,
            "productQuantity": 4,
            "productUnitPrice": 4,
            "expireAt": 946668601000
        },
        {
            "id": 3,
            "cartId": 1,
            "productId": "dfdfdf",
            "createdAt": 1493898820000,
            "updatedAt": 1493898820000,
            "amount": null,
            "offer": 23.23,
            "amountWithOffer": null,
            "taxes": null,
            "amountWithTaxes": null,
            "totalPayableAmount": null,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": null,
            "productQuantity": null,
            "productUnitPrice": null,
            "expireAt": 1493898820000
        },
        {
            "id": 4,
            "cartId": 1,
            "productId": "dfdfdf",
            "createdAt": 1493899099000,
            "updatedAt": 1493899099000,
            "amount": null,
            "offer": 23.23,
            "amountWithOffer": null,
            "taxes": null,
            "amountWithTaxes": null,
            "totalPayableAmount": null,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": null,
            "productQuantity": null,
            "productUnitPrice": null,
            "expireAt": 1493899099000
        },
        {
            "id": 5,
            "cartId": 1,
            "productId": "dfdfdf",
            "createdAt": 1493959373000,
            "updatedAt": 1493959373000,
            "amount": null,
            "offer": 23.23,
            "amountWithOffer": null,
            "taxes": null,
            "amountWithTaxes": null,
            "totalPayableAmount": null,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": null,
            "productQuantity": null,
            "productUnitPrice": null,
            "expireAt": 1493959373000
        },
        {
            "id": 6,
            "cartId": 1,
            "productId": "dfdfdf",
            "createdAt": 1493961518000,
            "updatedAt": 1493961518000,
            "amount": null,
            "offer": 23.23,
            "amountWithOffer": null,
            "taxes": null,
            "amountWithTaxes": null,
            "totalPayableAmount": null,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": null,
            "productQuantity": null,
            "productUnitPrice": null,
            "expireAt": 1493975919000
        },
        {
            "id": 7,
            "cartId": 1,
            "productId": "dfdfdf",
            "createdAt": 1493974361000,
            "updatedAt": 1493974361000,
            "amount": 0,
            "offer": 23.23,
            "amountWithOffer": 0,
            "taxes": 0,
            "amountWithTaxes": 0,
            "totalPayableAmount": 0,
            "productName": "Test Product",
            "productMRP": 345,
            "productSelling": 456,
            "discount":56,
            "productImage": "p/I/P/7/d/MINIP7W1IIE07-icon.jpg",
            "isPersistant": null,
            "productQuantity": null,
            "productUnitPrice": null,
            "expireAt": 1493988761000
        }
    ],
    "addressList": [
        {
            "id": 1,
            "cartId": 1,
            "addressId": 76,
            "type": "76tt8yg"
        },
        {
            "id": 2,
            "cartId": 1,
            "addressId": 9,
            "type": "998"
        }
    ],
    "payment": {
        "id": 1,
        "cartId": 1,
        "paymentMethodId": 4,
        "type": "xyz"
    },
    "deliveryMethod": {
        "id": 1,
        "cartId": 1,
        "deliveryMethodId": 77,
        "type": "kjhlh"
    },
    "offersList": [
        {
            "id": 1,
            "cartId": 1,
            "offerId": 7,
            "type": "7"
        },
        {
            "id": 2,
            "cartId": 1,
            "offerId": 32,
            "type": "32"
        },
        {
            "id": 4,
            "cartId": 1,
            "offerId": 87,
            "type": "yug"
        }
    ]
};