export const DATA_NB = {
    "CC": {
        "amex debit card": {
            "id": 9,
            "idList": [],
            "name": "amex debit card",
            "code": "AMEX",
            "enable": true,
            "platformCode": null,
            "mode": "CC",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "ccnum": true,
                "ccexpmon": true,
                "ccvv": true,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "ccexpyr": true,
                "state": false,
                "productinfo": true,
                "ccname": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        },
        "dinersclub debit card": {
            "id": 10,
            "idList": [],
            "name": "dinersclub debit card",
            "code": "DINR",
            "enable": true,
            "platformCode": null,
            "mode": "CC",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "ccnum": true,
                "ccexpmon": true,
                "ccvv": true,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "ccexpyr": true,
                "state": false,
                "productinfo": true,
                "ccname": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        },
        "mastercard debit card": {
            "id": 8,
            "idList": [],
            "name": "mastercard debit card",
            "code": "MAST",
            "enable": true,
            "platformCode": null,
            "mode": "CC",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "ccnum": true,
                "ccexpmon": true,
                "ccvv": true,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "ccexpyr": true,
                "state": false,
                "productinfo": true,
                "ccname": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        }
    },
    "EMI": {
        "emi": {
            "id": 14,
            "idList": [],
            "name": "emi",
            "code": "EMI",
            "enable": true,
            "platformCode": null,
            "mode": "EMI",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "ccnum": true,
                "ccexpmon": true,
                "ccvv": true,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "ccexpyr": true,
                "state": false,
                "productinfo": true,
                "ccname": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        }
    },
    "NEFT": {
        "neft": {
            "id": 4,
            "idList": [],
            "name": "neft",
            "code": "NEFT",
            "enable": true,
            "platformCode": null,
            "mode": "NEFT",
            "topBank": false,
            "attributeNames": {
                "email": true
            },
            "attributeValueMap": {}
        }
    },
    "NB": {
        "Karnataka Bank": {
            "id": 27,
            "idList": [],
            "name": "karnataka bank",
            "code": "KRKB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "State Bank of Hyderabad": {
            "id": 30,
            "idList": [],
            "name": "state bank of hyderabad",
            "code": "SBHB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "DCB Bank - Corporate Netbanking": {
            "id": 45,
            "idList": [],
            "name": "dcb bank - corporate netbanking",
            "code": "DCBCORP",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Deutsche Bank": {
            "id": 42,
            "idList": [],
            "name": "deutsche bank",
            "code": "DSHB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "ING Vysya Bank": {
            "id": 50,
            "idList": [],
            "name": "ing vysya bank",
            "code": "INGB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "South Indian Bank": {
            "id": 33,
            "idList": [],
            "name": "south indian bank",
            "code": "SOIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Canara Bank": {
            "id": 39,
            "idList": [],
            "name": "canara bank",
            "code": "CABB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Kotak Bank": {
            "id": 43,
            "idList": [],
            "name": "kotak bank",
            "code": "162B",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "State Bank of Mysore": {
            "id": 31,
            "idList": [],
            "name": "state bank of mysore",
            "code": "SBMB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Citi Bank NetBanking": {
            "id": 41,
            "idList": [],
            "name": "citi bank netbanking",
            "code": "CITNB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Indian Bank": {
            "id": 23,
            "idList": [],
            "name": "indian bank",
            "code": "INDB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Punjab National Bank - Retail Banking": {
            "id": 46,
            "idList": [],
            "name": "punjab national bank - retail banking",
            "code": "PNBB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Industrial Development Bank of India": {
            "id": 22,
            "idList": [],
            "name": "industrial development bank of india",
            "code": "IDBB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "State Bank of Bikaner and Jaipur": {
            "id": 29,
            "idList": [],
            "name": "state bank of bikaner and jaipur",
            "code": "SBBJB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Jammu and Kashmir Bank": {
            "id": 26,
            "idList": [],
            "name": "jammu and kashmir bank",
            "code": "JAKB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Bank of India": {
            "id": 15,
            "idList": [],
            "name": "bank of india",
            "code": "BOIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Indian Overseas Bank": {
            "id": 25,
            "idList": [],
            "name": "indian overseas bank",
            "code": "INOB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Yes Bank": {
            "id": 37,
            "idList": [],
            "name": "yes bank",
            "code": "YESB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Catholic Syrian Bank": {
            "id": 44,
            "idList": [],
            "name": "catholic syrian bank",
            "code": "CSBN",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Central Bank Of India": {
            "id": 17,
            "idList": [],
            "name": "central bank of india",
            "code": "CBIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Union Bank - Corporate Netbanking": {
            "id": 48,
            "idList": [],
            "name": "union bank - corporate netbanking",
            "code": "UBIBC",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Punjab National Bank-Corporate": {
            "id": 49,
            "idList": [],
            "name": "punjab national bank-corporate",
            "code": "CPNB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Development Credit Bank": {
            "id": 19,
            "idList": [],
            "name": "development credit bank",
            "code": "DCBB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Federal Bank": {
            "id": 20,
            "idList": [],
            "name": "federal bank",
            "code": "FEDB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Dena Bank": {
            "id": 21,
            "idList": [],
            "name": "dena bank",
            "code": "DENN",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Bank of Maharashtra": {
            "id": 16,
            "idList": [],
            "name": "bank of maharashtra",
            "code": "BOMB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Corporation Bank": {
            "id": 18,
            "idList": [],
            "name": "corporation bank",
            "code": "CRPB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "State Bank of Travancore": {
            "id": 32,
            "idList": [],
            "name": "state bank of travancore",
            "code": "SBTB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "United Bank Of India": {
            "id": 35,
            "idList": [],
            "name": "united bank of india",
            "code": "UNIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "CityUnion": {
            "id": 38,
            "idList": [],
            "name": "cityunion",
            "code": "CUBB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Saraswat Bank": {
            "id": 47,
            "idList": [],
            "name": "saraswat bank",
            "code": "SRSWT",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "IndusInd Bank": {
            "id": 24,
            "idList": [],
            "name": "indusind bank",
            "code": "INIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Karur Vysya": {
            "id": 28,
            "idList": [],
            "name": "karur vysya",
            "code": "KRVB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "State Bank of Patiala": {
            "id": 40,
            "idList": [],
            "name": "state bank of patiala",
            "code": "SBPB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "Vijaya Bank": {
            "id": 36,
            "idList": [],
            "name": "vijaya bank",
            "code": "VJYB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        }
    },
    "WALLET": {
        "payu": {
            "id": 54,
            "idList": [],
            "name": "payu",
            "code": "MIGRATE_PAYU",
            "enable": true,
            "platformCode": null,
            "mode": "WALLET",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "state": false,
                "productinfo": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        },
        "payumoney": {
            "id": 51,
            "idList": [],
            "name": "payumoney",
            "code": "PAYUW",
            "enable": true,
            "platformCode": null,
            "mode": "WALLET",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "state": false,
                "productinfo": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        }
    },
    "PAYTM": {
        "paytm": {
            "id": 53,
            "idList": [],
            "name": "paytm",
            "code": "PAYTM",
            "enable": true,
            "platformCode": null,
            "mode": "PAYTM",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        }
    },
    "COD": {
        "cash on delivery": {
            "id": 13,
            "idList": [],
            "name": "cash on delivery",
            "code": "COD",
            "enable": true,
            "platformCode": null,
            "mode": "COD",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        }
    },
    "MOBIKWIK": {
        "mobikwik": {
            "id": 52,
            "idList": [],
            "name": "mobikwik",
            "code": "MOBIKWIK",
            "enable": true,
            "platformCode": null,
            "mode": "MOBIKWIK",
            "topBank": false,
            "attributeNames": {},
            "attributeValueMap": {}
        }
    },
    "NB-top": {
        "Union Bank of India": {
            "id": 34,
            "idList": [],
            "name": "union bank of india",
            "code": "UBIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": true,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "State Bank of India": {
            "id": 12,
            "idList": [],
            "name": "state bank of india",
            "code": "SBIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": true,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "AXIS Bank NetBanking": {
            "id": 3,
            "idList": [],
            "name": "axis bank netbanking",
            "code": "AXIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": true,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "HDFC Bank": {
            "id": 5,
            "idList": [],
            "name": "hdfc bank",
            "code": "HDFB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": true,
            "attributeNames": {},
            "attributeValueMap": {}
        },
        "ICICI Netbanking": {
            "id": 11,
            "idList": [],
            "name": "icici netbanking",
            "code": "ICIB",
            "enable": true,
            "platformCode": null,
            "mode": "NB",
            "topBank": true,
            "attributeNames": {},
            "attributeValueMap": {}
        }
    },
    "DC": {
        "visa debit card": {
            "id": 6,
            "idList": [],
            "name": "visa debit card",
            "code": "MAESTRO CARD",
            "enable": false,
            "platformCode": null,
            "mode": "DC",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "ccnum": true,
                "ccexpmon": true,
                "ccvv": true,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "ccexpyr": true,
                "state": false,
                "productinfo": true,
                "ccname": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        },
        "maestro debit card": {
            "id": 7,
            "idList": [],
            "name": "maestro debit card",
            "code": "SMAE",
            "enable": true,
            "platformCode": null,
            "mode": "DC",
            "topBank": false,
            "attributeNames": {
                "country": false,
                "firstname": true,
                "address2": false,
                "city": false,
                "address1": false,
                "ccnum": true,
                "ccexpmon": true,
                "ccvv": true,
                "lastname": false,
                "zipcode": false,
                "phone": true,
                "additional_charges": false,
                "ccexpyr": true,
                "state": false,
                "productinfo": true,
                "ccname": true,
                "email": true,
                "bankcode": true
            },
            "attributeValueMap": {}
        }
    }
}