import CONSTANTS from "./constants";

export const product = {
    language: CONSTANTS.LANGUAGE_HI, // do not transalate this 
    search_bar_text: "सर्च प्रोडक्ट्स/ कैटेगरीज",
    coupon_text: "EMI बैंकों में न्यूनतम रु. 3000 और बजाज फिनसर्व में रु. 4500 की खरीद पर उपलब्ध है",
    cod_available:"कैश ऑन डिलीवरी उपलब्ध (आप डिलीवरी के समय भुगतान कर सकते हैं",
    delivery_details:"डिलिवरी डिटेल्स",
    best_matching_heading:"बेस्ट मैचिंग इन-स्टॉक प्रोडक्ट्स",
    available_on_request:"रिक्वेस्ट पर उपलब्ध",
    consider_these_available_items:"इन उपलब्ध प्रोडक्ट पर विचार करें",
    have_doubts_regarding_this_product:"विशिष्ट जानकारी खोज रहे हैं",
    ask_now:"सवाल पूछें",
    be_the_first_one_to_review:"इस प्रोडक्ट के लिए समीक्षा प्रदान करने वाले पहले व्यक्ति बनें",
    rating_review:"समीक्षा और रेटिंग",
    product_videos:"प्रोडक्ट वीडियो",
    read_more:"और पढ़ें",
    about_this_product:"इस प्रोडक्ट के बारे में",
    key_features:"प्रमुख विशेषताएं",
    days_help_desk:"365 दिन हैल्प डेस्क",
    product_details:"प्रोडक्ट विवरण",
    free_delivery:"फ्री डिलिवरी",
    no_shipping_charge:"इस आर्डर पर कोई शिपिंग शुल्क नहीं",
    moglix_benefits:"मोगलिक्स के फायदे",
    return_policy:"रिटर्न पॉलिसी",
    add_to_cart:"कार्ट में डालें",
    buy_now:"अभी खरीदें",
    more_from:"और एक्सप्लोर करें",
    use_code:"कोड का इस्तेमाल करें",
    best_of_moglix:"मोगलिक्स का बेस्ट",
    frequently_bought_together:"इस प्रोडक्ट  को खरीदने वाले ग्राहकों ने ये भी खरीदाइस",
    min_emi_text:"EMI बैंकों में न्यूनतम रु. 3000 और बजाज फिनसर्व में रु. 4500 की खरीद पर उपलब्ध ह",
    emi_gst_text_part1:"जीएसटी चालान प्राप्त करें और व्यापार खरीद पर",
    emi_gst_text_part2:"तक की बचत करें।",
    write_review:"समीक्षा लिखें",
    recently_viewed:"हाल ही में देखे गए प्रोडक्ट",
    view_more_faq:"अधिक बार पूछे जाने वाले प्रश्न देखें",
    show_all_key_features:"सभी प्रमुख विशेषताएं दिखाएं",
    free_details:"",
    buy_it_again:"फिर से खरीदें"

}  