import CONSTANTS from "./constants";

export const product = {
    language: CONSTANTS.LANGUAGE_EN, // do not transalate this 
    search_bar_text: "Search Products/Categories",
    coupon_text: "EMIs Available on minimum  purchase of Rs. 3000 across banks and Rs. 4500 for Bajaj Finserv",
    cod_available:"COD Available",
    delivery_details:"Delivery Details",
    best_matching_heading:"Best Matching In-Stock Products",
    available_on_request:"AVAILABLE ON REQUEST",
    consider_these_available_items:"Consider These Available Items",
    have_doubts_regarding_this_product:"Have doubts regarding this product",
    ask_now:"ASK NOW",
    be_the_first_one_to_review:"Be the first one to provide review for this product",
    rating_review:"Reviews & Ratings",
    product_videos:"Product Videos",
    read_more:"Read More",
    about_this_product:"About This Product",
    key_features:"Key Features",
    days_help_desk:"365 Days Help Desk",
    product_details:"Product Details",
    free_delivery:"Free Delivery",
    no_shipping_charge:"No shipping charge on this order",
    moglix_benefits:"Moglix Benefits",
    return_policy:"Return & Warranty Policy",
    add_to_cart:"ADD TO CART",
    buy_now:"BUY NOW",
    more_from:"More from ___categoryName___",
    more_from_brand:"More from ___brandName___ ___categoryName___",
    use_code:"Use Code",
    best_of_moglix:"Best of Moglix",
    frequently_bought_together:"Frequently Bought Together",
    min_emi_text:"On min. purchase of Rs. 3000 across banks and Rs. 4500 for Bajaj Finserv",
    emi_gst_text_part1:"Get GST invoice and save up to",
    emi_gst_text_part2:"on business purchases",
    write_review:"WRITE A REVIEW",
    recently_viewed:"Recently Viewed",
    view_more_faq:"MORE FAQs",
    viewMore:"VIEW",
    show_all_key_features:"Show All Key Features",
    show_all_specifination: "Show All Specifications",
    buy_it_again:"Buy it Again",
    interested_to_buy_in_bulk:"Interested to buy in bulk?",
    get_quote:"GET QUOTE",
    incl_of_taxes:"Incl. of all taxes",
    get_customized_price:"Get customized price",
    slide_to_request:"SLIDE TO RAISE REQUEST",
    open_app:"Open App",
    enter_your_pincode:"Enter your pincode",
    check_serviceability:"Check serviceability at your location",
    gst:"GST",
    off:"OFF",
    reviews:"Reviews",
    review:"Review",
    offers_coupons:"Offers and Coupons",
    emi_available:"EMI's Available",
    brand_store:"Brand Store",
    brand:"Brand",
    avg_rating_based_on:"Average Rating based on",
    ratings_and:"ratings and",
    reviews_small:'reviews',
    verified_purchase:"Verified Purchase",
    view:"VIEW",
    check:"CHECK",
    gst_invoice:"GST Invoice",
    available:"Available",
    secure:"Secure",
    payments:"Payments",
    days_365:"365 Days",
    help_desk:"Help Desk",
    upto_7days:"Upto ___number___ Days",
    returnable:"Returnable",
    wrong:"Wrong",
    product:"Product",
    damaged:"Damaged",
    defective:"Defective",
    download_moglix_app:"Download Moglix App",
    get_100_off:"Get ₹100 Off",
    on_your_first_order:"on your first order.",
    similar_products:"Similar Products",
    buy_more_save_more:"Buy More and Save More",
    buy_more:"Buy More",
    frequently_asked_questions:"Frequently Asked Questions",
    customer_reviews:"Customer Reviews",
    displaying_questions:"Displaying Questions",
    more_helpful_review:"MORE HELPFUL REVIEWS",
    explore_now:"Explore Now",
    get_best_price:"GET BEST PRICE",
    store:"Store",
    product_specifications:"Product Specifications",
    available_coupons:"Available Coupons",
    and_get:"Get",
     //product info key
    "specifications":"specifications",
    "images":"images",
    "product details":"product details",
    "key features": 'key features',
    "videos": 'videos',
    invalid_pincode_validation:"Invalid pincode provided",
    prepaid_payment_only:"Prepaid payment only",
    accordian_list1_label: 'Related Searches',
    accordian_list2_label: 'Popular Brand Categories',
    accordian_list3_label: 'Shop by Related Categories',
    slide_to_raise_request:'Slide to Raise Request',
    // we_will_get_in_touch:"We will get in touch with you on",
    successfully_added_to_wishlist:"Successfully added to Wishlist",
    view_in_stock:"VIEW IN-STOCK",
    pincode_shipping_applicable: 'Shipping applicable',
    pincode_on_this_order: 'On this order',
    pincode_delivery_text: 'Delivery available at ___pincode___ in ___deliveryDays___',
    pincode_delivery_unavalible: 'Delivery unavailable at ___pincode___',
    pincode_pay_at_time_delivery: 'You can pay at the time of delivery',
    coupon_static_text:'Pay online & get EXTRA ___coupon_discount___ OFF on  ___brandName ___ ___categoryName___',
    requested_successfully:"REQUESTED SUCCESSFULLY",
    coupon_text1:"Pay online & get EXTRA ___discount___ OFF",
    looking_for_category:"Looking for ___categoryName___",
    min_cart_value: 'Min cart value ___count___',
    see_more_coupons: 'SEE ___promoCodes___ MORE COUPON(S)',
    prepaid_discount_text: `Using UPI, EMI, Credit/Debit Card, Net Banking, Wallets on min. cart value of ___minimumCartValue___ in ___brandName___ ___categoryName___`,
    get_rfq_text_1: 'Purchase item in bulk quantity',
    get_rfq_text_2: 'Get at best price for your business',
    get_rfq_text_3: 'We will get in touch with you on',
    get_rfq_text_4: 'Thank you! Our support member will get in touch with you within 24 hours.',
    show_more: 'SHOW MORE',
    show_less: 'SHOW LESS',
    of:'/',
    emis_availaible:'EMIs Available ',
    brand_store_text:'___brand___ Store',
    missing: 'Missing',
    buy: 'Buy',
    // Listing pages translation
    sort_by: 'Sort By',
    popularity: 'Popularity',
    low_price: 'Low Price',
    high_price: 'High Price',
    filters: 'Filters',
    showing: 'Showing',
    out_of: 'out of',
    products: 'products',
    clear_all: 'CLEAR ALL',
    apply: 'APPLY',
    above: 'Above',
    price_low_high: 'Price - Low To High',
    price_high_low: 'Price - High To Low',
    send_query: 'SEND QUERY',
    easy_emi_availble: 'Easy EMI available',
    available_request: 'Available on Request',
    product_added_successfully: 'Product added successfully',
    by: 'By',
    enter_the_req_qty: 'Enter the required quantity',
    kindly_enter_valid_qty: 'Kindly enter valid quantity.',
    qty_should_contain_digits: 'Quantity should contain only digits.',
    rfq_qty_should_be_greate_than: 'RFQ Quantity should be greater than',
    kindly_enter_full_name: 'Kindly enter your full name.',
    special_chars_not_allowed: 'Special characters are not allowed.',
    full_name: 'Full Name',
    kindly_enter_your_email: 'Kindly enter your email id.',
    kindly_enter_valid_email_id: 'Kindly enter valid email id.',
    email: 'Email',
    kindly_enter_your_mobile_no: 'Kindly enter your mobile no.',
    mobile_should_contain_digits: 'Mobile should contain only digits.',
    mobile_10_digits: 'Mobile should contain 10 digits.',
    mobile: 'Mobile',
    invalid_pincode: 'Invalid pincode',
    pincode_should_contain_digits: 'Pincode should contain only digits.',
    pincode_6_digits: 'Pincode should contain 6 digits.',
    pincode: 'Pincode',
    kindly_enter_your_city_name: 'Kindly enter your city name.',
    kindly_enter_valid_city_name: 'Kindly enter your valid city name.',
    city_30_digits: 'City should contain 30 characters.',
    city: 'City',
    i_dont_know_my_pincode: "I don't know my pincode",
    description_should_contain_chars: 'Description should contain only characters.',
    mention_details_you_like_to_share: "Mention details that you'd like to share...",
    business_purchase: 'Business Purchase',
    add_gstin_for_verification: 'Add GSTIN for verification',
    kindly_enter_gstin: 'Kindly enter GSTIN.',
    kindly_enter_valid_gstin: 'Kindly enter valid GSTIN.',
    submit_your_requirement: 'SUBMIT YOUR REQUIREMENT',
    thanks_for_submitting_query: 'Thanks for submitting the query.',
    get_in_touch: 'Our support member will get in touch with you',
    within_24_hours: 'within 24 hours',
    call_us: 'CALL US',
    or: 'OR',
    whatsapp_us: 'WHATSAPP US',
    further_assistance: 'For further assistance Call or Whatsapp',
    also_mail_us_at: 'You can also mail us at',
    show_similar_products: 'SHOW SIMILAR PRODUCTS',
    explore_available_products: 'EXPLORE AVAILABLE PRODUCTS',
    select_variant: 'Select Variant',
    select: 'Select',
    continue: 'CONTINUE',
    buy_with_gst_for_business_in_bulk: 'Buy with GST for Business in Bulk',
    get_customised_best_price: 'Get customised & best price',
    raise_request: 'RAISE REQUEST',
    kindly_select_a_valid_product_type: 'Kindly select a valid product type',
    moglix_insight: 'Moglix Insight',
    top: 'Top',
    price_range_of: 'price range of',
    categories_of: 'categories of',
    in_price_range: 'in price range of',
    of_users_prefer: 'of users prefer',
    in_other_price_range: 'in other price range',
    brands_of: 'brands of',
    of1: 'of',
    brand1: 'brand',
    of_other_brands: 'of other brands',
    of_users_buy: 'of users buy',
    in: 'in',
    shop_by: 'Shop by',
    range: 'Range',
    are_you_looking_for: 'Are you looking for',
    shop: 'Shop',
    online: 'Online',
    pay_online_get_extra: 'Pay online & get EXTRA',
    using: 'Using',
    wallets: 'UPI, EMI, Credit/Debit Card, Net Banking, Wallets',
    on_min_cart_value: 'on min. cart value of',
    on: 'on',
    moglix_offers_quality_genuine: 'Moglix offers superior quality and genuine',
    from_renowned_brand: 'from a renowned brand',
    brand_cat_heading: 'Easily browse through our assortment and explore more about price, specifications, availability, and deals online for',
    brand_cat_desc: 'Buy these productsat best prices and get them delivered at your doorstep across India.',
    home: 'Home',
    top_selling: 'Top Selling',
    price_list_india: 'Price List in India',
    latest_models: 'Latest Models',
    price: 'Price',
    discount: 'Discount',
    data_last_updated_on: 'This data was last updated on',
    genuine_products_from: 'Genuine Products from',
    at_the_best_price: 'at the Best Prices Online at Moglix',
    brand_desc: 'products are procured through reliable distributors and dealers in India and several other countries worldwide. We, at Moglix, offer more than',
    brand_desc2: 'that are listed on our online store. These are suitable for personal or commercial use in various industries, homes, businesses and offices. These listings have been properly curated and arranged in various product categories such as',
    brand_desc3: 'to provide easy navigation and seamless user experience.',
    brand_desc4: 'Moglix is one stop solution if you are looking online for best deals and offers on',
    brand_desc5: 'products. We also offer the option of bulk buying or wholesale prices on these products. Having a pan India presence including major cities like Delhi NCR, Mumbai, Chennai, Bengaluru, Kolkata, Chennai, Pune, Jaipur, Hyderabad, and Ahmedabad, Moglix provides timely doorstep delivery nation-wide.',
    products_by: 'product by',
    popular_categories: 'Popular Categories',
    similar_category: 'Similar Category',
    related_brands: 'Related Brands',
    related_category: 'Related Category',
    buy_online: 'Products Online at Best Price',
    shop_online: 'products at best prices in India. Shop online for',
    brand_title: 'products at Moglix. Free Delivery & COD options across India.',
    select_language: 'Select Language'
}