import CONSTANTS from "./constants";

export const product = {
    language: CONSTANTS.LANGUAGE_EN, // do not transalate this 
    search_bar_text: "Search Products/Categories",
    coupon_text: "EMIs Available on minimum  purchase of Rs. 3000 across banks and Rs. 4500 for Bajaj Finserv",
    cod_available:"COD Available",
    delivery_details:"Delivery Details",
    best_matching_heading:"Best Matching In-Stock Products",
    available_on_request:"AVAILABLE ON REQUEST",
    consider_these_available_items:"Consider These Available Items",
    have_doubts_regarding_this_product:"Have doubts regarding this product",
    ask_now:"ASK NOW",
    be_the_first_one_to_review:"Be the first one to provide review for this product",
    rating_review:"Reviews & Ratings",
    product_videos:"Product Videos",
    read_more:"Read More",
    about_this_product:"About This Product",
    key_features:"Key Features",
    days_help_desk:"365 Days Help Desk",
    product_details:"Product Details",
    free_delivery:"Free Delivery",
    no_shipping_charge:"No shipping charge on this order",
    moglix_benefits:"Moglix Benefits",
    return_policy:"Return & Warranty Policy",
    add_to_cart:"ADD TO CART",
    buy_now:"BUY NOW",
    more_from:"More from ___categoryName___",
    more_from_brand:"More from ___brandName___ ___categoryName___",
    use_code:"Use Code",
    best_of_moglix:"Best of Moglix",
    frequently_bought_together:"Frequently Bought Together",
    min_emi_text:"On min. purchase of Rs. 3000 across banks and Rs. 4500 for Bajaj Finserv",
    emi_gst_text_part1:"Get GST invoice and save up to",
    emi_gst_text_part2:"on business purchases",
    write_review:"WRITE A REVIEW",
    recently_viewed:"Recently Viewed",
    view_more_faq:"MORE FAQs",
    viewMore:"VIEW",
    show_all_key_features:"Show All Key Features",
    show_all_specifination: "Show All Specifications",
    buy_it_again:"Buy it Again",
    interested_to_buy_in_bulk:"Interested to buy in bulk?",
    get_quote:"GET QUOTE",
    incl_of_taxes:"Incl. of all taxes",
    get_customized_price:"Get customized price",
    slide_to_request:"SLIDE TO RAISE REQUEST",
    open_app:"Open App",
    enter_your_pincode:"Enter your pincode",
    check_serviceability:"Check serviceability at your location",
    gst:"GST",
    off:"OFF",
    reviews:"Reviews",
    offers_coupons:"Offers and Coupons",
    emi_available:"EMI's Available",
    brand_store:"Brand Store",
    brand:"Brand",
    avg_rating_based_on:"Average Rating based on",
    ratings_and:"ratings and",
    reviews_small:'reviews',
    verified_purchase:"Verified Purchase",
    view:"VIEW",
    check:"CHECK",
    gst_invoice:"GST Invoice",
    available:"Available",
    secure:"Secure",
    payments:"Payments",
    days_365:"365 Days",
    help_desk:"Help Desk",
    upto_7days:"Upto ___number___ Days",
    returnable:"Returnable",
    wrong:"Wrong",
    product:"Product",
    damaged:"Damaged",
    defective:"Defective",
    download_moglix_app:"Download Moglix App",
    get_100_off:"Get ₹100 Off",
    on_your_first_order:"on your first order.",
    similar_products:"Similar Products",
    buy_more_save_more:"Buy More and Save More",
    buy_more:"Buy More",
    frequently_asked_questions:"Frequently Asked Questions",
    customer_reviews:"Customer Reviews",
    displaying_questions:"Displaying Questions",
    more_helpful_review:"MORE HELPFUL REVIEWS",
    explore_now:"Explore Now",
    get_best_price:"GET BEST PRICE",
    store:"Store",
    product_specifications:"Product Specifications",
    available_coupons:"Available Coupons",
    and_get:"Get",
     //product info key
    "specifications":"specifications",
    "images":"images",
    "product details":"product details",
    "key features": 'key features',
    "videos": 'videos',
    invalid_pincode_validation:"Invalid pincode provided",
    prepaid_payment_only:"Prepaid payment only",
    accordian_list1_label: 'Related Searches',
    accordian_list2_label: 'Popular Brand Categories',
    accordian_list3_label: 'Shop by Related Categories',
    slide_to_raise_request:'Slide to Raise Request',
    // we_will_get_in_touch:"We will get in touch with you on",
    successfully_added_to_wishlist:"Successfully added to Wishlist",
    view_in_stock:"VIEW IN-STOCK",
    pincode_shipping_applicable: 'Shipping applicable',
    pincode_on_this_order: 'On this order',
    pincode_delivery_text: 'Delivery available at ___pincode___ in ___deliveryDays___',
    pincode_delivery_unavalible: 'Delivery unavailable at ___pincode___',
    pincode_pay_at_time_delivery: 'You can pay at the time of delivery',
    coupon_static_text:'Save instantly ___coupon_discount___ with online payment.',
    requested_successfully:"REQUESTED SUCCESSFULLY",
    coupon_text1: "Save ___discount___ instantly with online payment.",
    looking_for_category:"Looking for ___categoryName___",
    min_cart_value: 'Min cart value ___count___',
    see_more_coupons: 'SEE ___promoCodes___ MORE COUPON(S)',
    prepaid_discount_text: `via UPI, EMI, Credit/Debit Card, Net Banking, Wallets on min. cart value of ₹___minimumCartValue___ in ___brandName___ ___categoryName___`,
    prepaid_discount_text_alt: ` UPI, EMI, Credit/Debit Card, Net Banking, Wallets.`,
    via:`via`,
    get_rfq_text_1: 'Purchase item in bulk quantity',
    get_rfq_text_2: 'Get at best price for your business',
    get_rfq_text_3: 'We will get in touch with you on',
    get_rfq_text_4: 'Thank you! Our support member will get in touch with you within 24 hours.',
    show_more: 'SHOW MORE',
    show_less: 'SHOW LESS',
    of:'/',
    emis_availaible:'EMIs Available ',
    brand_store_text:'___brand___ Store',
    missing: 'Missing',
    buy: 'Buy'
}