import CONSTANTS from "./constants";

export const product = {
    language: CONSTANTS.LANGUAGE_HI, // do not transalate this 
    search_bar_text: "सर्च प्रोडक्ट्स/ कैटेगरीज",
    coupon_text: "EMI बैंकों में न्यूनतम रु. 3000 और बजाज फिनसर्व में रु. 4500 की खरीद पर उपलब्ध है",
    cod_available:"कैश ऑन डिलीवरी उपलब्ध",
    delivery_details:"डिलिवरी डिटेल्स",
    best_matching_heading:"बेस्ट मैचिंग इन-स्टॉक प्रोडक्ट्स",
    available_on_request:"रिक्वेस्ट पर उपलब्ध",
    consider_these_available_items:"इन उपलब्ध प्रोडक्ट पर विचार करें",
    have_doubts_regarding_this_product:"विशिष्ट जानकारी खोज रहे हैं",
    ask_now:"सवाल पूछें",
    be_the_first_one_to_review:"इस प्रोडक्ट के लिए समीक्षा प्रदान करने वाले पहले व्यक्ति बनें",
    rating_review:"समीक्षा और रेटिंग",
    product_videos:"प्रोडक्ट वीडियो",
    read_more:"और पढ़ें",
    about_this_product:"इस प्रोडक्ट के बारे में",
    key_features:"प्रमुख विशेषताएं",
    days_help_desk:"365 दिन हैल्प डेस्क",
    product_details:"प्रोडक्ट विवरण",
    free_delivery:"फ्री डिलिवरी",
    no_shipping_charge:"इस आर्डर पर कोई शिपिंग शुल्क नहीं",
    moglix_benefits:"मोगलिक्स के फायदे",
    return_policy:"रिटर्न पॉलिसी",
    add_to_cart:"कार्ट में डालें",
    buy_now:"अभी खरीदें",
    more_from:"एक्सप्लोर करें दूसरे ___categoryName___",
    more_from_brand:"एक्सप्लोर करें दूसरे ___brandName___ ___categoryName___",
    use_code:"कोड का इस्तेमाल करें",
    best_of_moglix:"मोग्लिक्स के सर्वश्रेष्ठ प्रोडक्ट",
    frequently_bought_together:"इस प्रोडक्ट  को खरीदने वाले ग्राहकों ने ये भी खरीदा है",
    min_emi_text:"EMI बैंकों में न्यूनतम रु. 3000 और बजाज फिनसर्व में रु. 4500 की खरीद पर उपलब्ध है",
    emi_gst_text_part1:"जीएसटी चालान प्राप्त करें और व्यापार खरीद पर",
    emi_gst_text_part2:"तक की बचत करें।",
    write_review:"समीक्षा लिखें",
    recently_viewed:"हाल ही में देखे गए प्रोडक्ट",
    view_more_faq:"अधिक बार पूछे जाने वाले प्रश्न",  
    show_all_key_features:"सभी प्रमुख विशेषताएं दिखाएं",
    show_all_specifination: "सभी स्पेसिफिकेशंस दिखाएं",
    free_details:"",
    buy_it_again:"फिर से खरीदें",
    interested_to_buy_in_bulk:"थोक में खरीदारी के इच्छुक?",
    get_customized_price:"कस्टमाइज़्ड प्राइस पाएं",
    get_quote:"कोटेशन प्राप्त करें",
    incl_of_taxes:"सभी टैक्स सहित",
    slide_to_request:"कोटेशन रिक्वेस्ट करने के लिए स्लाइड करें",
    open_app:"ऐप खोलें",
    enter_your_pincode:"अपना पिनकोड दर्ज करें",
    check_serviceability:"अपने स्थान पर सेवा की योग्यता की जांच करें",
    gst:"जीएसटी",
    off:"छूट",
    reviews:"रिव्यू",
    review:"रिव्यू",
    offers_coupons:"ऑफर्स और कूपन्स",
    emi_available:"ईएमआई उपलब्ध",
    brand:"ब्रांड",
    brand_store:"ब्रांड स्टोर",
    ratings_and:"रेटिंग और",
    reviews_small:"समीक्षा",
    avg_rating_based_on:"रेटिंग औसत के आधार पर",
    verified_purchase:"वेरिफ़ाई की गई खरीद",
    view:"देखें",
    check:"चेक करें",
    gst_invoice:"जीएसटी चालान ",
    available:"उपलब्ध",
    secure:"सुरक्षित",
    payments:"भुगतान",
    days_365:"365 दिन",
    help_desk:" हैल्प डेस्क",
    upto_7days:"___number___ दिनों तक",
    returnable:"वापसी योग्य",
    wrong:"गलत",
    product:"प्रोडक्ट",
    damaged:"डैमेज हुआ",
    defective:"दोषपूर्ण",
    download_moglix_app:"मोग्लिक्स ऐप डाउनलोड करें",
    get_100_off:"Rs100 की छूट",
    on_your_first_order:" अपने पहले ऑर्डर पर",
    similar_products:"मिलते-जुलते प्रोडक्ट",
    buy_more_save_more:"अधिक खरीदें और अधिक बचत करें",
    buy_more:"अधिक खरीदें",
    frequently_asked_questions:"अक्सर पूछे जाने वाले सवाल",
    customer_reviews:"ग्राहक समीक्षा",
    displaying_questions:"प्रदर्शन कर रहे हैं सवाल",
    more_helpful_review:"अधिक उपयोगी समीक्षा",
    explore_now:"अभी एक्सप्लोर करें",
    get_best_price:"बेस्ट प्राइस पाएं",
    store:"स्टोर",
    product_specifications:"प्रोडक्ट स्पेसिफिकेशंस",
    available_coupons:"उपलब्ध कूपन",
    and_get:"प्राप्त करें",
    //product info key
    "specifications":"स्पेसिफिकेशंस",
    "images":"तस्वीरें",
    "product details":"प्रोडक्ट विवरण",
    "key features": 'प्रमुख विशेषताएं',
    "videos": 'वीडियो',
    invalid_pincode_validation:"गलत पिनकोड दिया गया",
    prepaid_payment_only:"केवल प्रीपेड भुगतान उपलब्ध है",
    accordian_list1_label: 'संबंधित प्रोडक्ट खोजें',
    accordian_list2_label: 'लोकप्रिय ब्रांड कैटेगरी',
    accordian_list3_label: 'संबंधित प्रोडक्ट की खरीदारी करें',
    slide_to_raise_request:'कोटेशन रिक्वेस्ट करने के लिए स्लाइड करें',
    // we_will_get_in_touch:"We will get in touch with you on",
    successfully_added_to_wishlist:"इच्छा सूची में सफलतापूर्वक जोड़ा गया",
    view_in_stock:"इन-स्टॉक देखें",
    pincode_shipping_applicable: 'शिपिंग लागू',
    pincode_on_this_order: 'इस आर्डर पर',
    pincode_delivery_text: 'वितरण ___deliveryDays___ में ___pincode___ पर उपलब्ध है',
    pincode_delivery_unavalible: '___pincode___ में डिलीवरी अनुपलब्ध है',
    pincode_pay_at_time_delivery: 'आप डिलीवरी के समय भुगतान कर सकते हैं',
    coupon_static_text:'भुगतान ऑनलाइन करें और ___brandName ___ ___categoryName___ पर ___coupon_discount___ की छूट प्राप्त करें।',
    requested_successfully:"रिक्वेस्ट सफल",
    coupon_text1:"भुगतान ऑनलाइन करें और ___discount___ की छूट प्राप्त करें।",
    looking_for_category:"क्या आप ___categoryName___ की तलाश कर रहे हैं",
    min_cart_value: '___count___ रुपये के न्यूनतम कार्ट मूल्य पर',
    see_more_coupons: '___promoCodes___ और कूपन देखें',
    prepaid_discount_text: `ऑनलाइन भुगतान करें और प्राप्त करें, 
    ___brandName___ ___categoryName___ में ___minimumCartValue___ के न्यूनतम कार्ट मूल्य पर यूपीआई, ईएमआई, क्रेडिट / डेबिट कार्ड, नेट बैंकिंग, वॉलेट का उपयोग करके भुगतान करते समय लागू`,
    get_rfq_text_1: 'बड़ी मात्रा में सामान खरीदें',
    get_rfq_text_2: 'अपने व्यवसाय के लिए सर्वोत्तम मूल्य प्राप्त करें',
    get_rfq_text_3: 'हम आपसे संपर्क करेंगे : ',
    get_rfq_text_4: 'शुक्रिया! हमारा समर्थन सदस्य 24 घंटे के भीतर आपसे संपर्क करेगा।',
    show_more: 'और दिखाएं',
    show_less: 'कम दिखाएं',
    of:'/',
    emis_availaible:'उपलब्ध EMIs:',
    brand_store_text:"___brand___ स्टोर",
    missing: 'मिसिंग',
    buy: 'खरीदें',
    // Listing pages translation
    sort_by: 'सॉर्ट बाय',
    popularity: 'लोकप्रियता',
    low_price: 'कम कीमत',
    high_price: 'उच्च कीमत',
    filters: 'फिल्टर',
    showing: 'दिखा रहा है',
    out_of: 'में से',
    products: 'प्रॉडक्ट्स',
    clear_all: 'फिल्टर हटाएं',
    apply: 'अप्लाई करें',
    above: 'ऊपर',
    price_low_high: 'कीमत - कम से ज्यादा',
    price_high_low: 'कीमत - ज्यादा से कम',
    send_query: 'रिक्वेस्ट भेजें',
    easy_emi_availble: 'आसान ईएमआई उपलब्ध',
    available_request: 'रिक्वेस्ट पर उपलब्ध',
    product_added_successfully: 'उत्पाद सफलतापूर्वक जोड़ा गया',
    by: 'द्वारा',
    enter_the_req_qty: 'आवश्यक मात्रा में दर्ज करें',
    kindly_enter_valid_qty: 'कृपया वैध मात्रा दर्ज करें।',
    qty_should_contain_digits: 'मात्रा में केवल अंक होने चाहिए।',
    rfq_qty_should_be_greate_than: 'आरएफक्यू मात्रा से अधिक होना चाहिए',
    kindly_enter_full_name: 'कृपया अपना पूरा नाम दर्ज करें।',
    special_chars_not_allowed: 'विशेष वर्णों की अनुमति नहीं है।',
    full_name: 'पूरा नाम',
    kindly_enter_your_email: 'कृपया अपना ईमेल आईडी दर्ज करें।',
    kindly_enter_valid_email_id: 'कृपया मान्य ईमेल आईडी दर्ज करें।',
    email: 'ईमेल',
    kindly_enter_your_mobile_no: 'कृपया अपना मोबाइल नंबर दर्ज करें।',
    mobile_should_contain_digits: 'मोबाइल में केवल अंक होने चाहिए।',
    mobile_10_digits: 'मोबाइल में 10 अंक होने चाहिए।',
    mobile: 'मोबाइल',
    invalid_pincode: 'अवैध पिनकोड',
    pincode_should_contain_digits: 'पिनकोड में केवल अंक होने चाहिए।',
    pincode_6_digits: 'पिनकोड में 6 अंक होने चाहिए।',
    pincode: 'पिनकोड',
    kindly_enter_your_city_name: ' कृपया अपने शहर का नाम दर्ज करें।',
    kindly_enter_valid_city_name: 'कृपया अपना वैध शहर का नाम दर्ज करें।',
    city_30_digits: 'सिटी में 30 कैरेक्टर होने चाहिए।',
    city: 'सिटी',
    i_dont_know_my_pincode: "मैं अपने पिनकोड पता नहीं है",
    description_should_contain_chars: 'विवरण में केवल वर्ण होने चाहिए।',
    mention_details_you_like_to_share: "उन विवरणों का उल्लेख करें जिन्हें आप साझा करना चाहते हैं ..।",
    business_purchase: 'कारोबारी खरीददारी',
    add_gstin_for_verification: 'सत्यापन के लिए जीएसटीआईएन जोड़ें',
    kindly_enter_gstin: 'कृपया जीएसटीआईएन दर्ज करें।',
    kindly_enter_valid_gstin: 'कृपया वैध जीएसटीआईएन दर्ज करें।',
    submit_your_requirement: 'अपनी आवश्यकता सबमिट करें',
    thanks_for_submitting_query: 'क्वेरी सबमिट करने के लिए धन्यवाद।',
    get_in_touch: 'हमारे सहायक सदस्य आपसे संपर्क करेंगे',
    within_24_hours: '24 घंटे के भीतर',
    call_us: 'हमें बुलाओ',
    or: 'या',
    whatsapp_us: 'व्हाट्सएप हमें',
    further_assistance: 'आगे की सहायता के लिए कॉल या वॉट्सऐप करें',
    also_mail_us_at: 'आप हमें मेल भी कर सकते हैं',
    show_similar_products: 'सिमिलर प्रॉडक्ट्स दिखाएं',
    explore_available_products: 'उपलब्ध उत्पादों का विस्तार करें',
    select_variant: 'वैरिएंट का चयन करें',
    select: 'चुनें',
    continue: 'जारी रखें',
    buy_with_gst_for_business_in_bulk: 'थोक में व्यापार के लिए जीएसटी के साथ खरीदें',
    get_customised_best_price: 'अनुकूलित और सर्वोत्तम मूल्य प्राप्त करें',
    raise_request: 'रिक्वेस्ट करें',
    kindly_select_a_valid_product_type: 'कृपया एक वैध उत्पाद प्रकार का चयन करें',
    moglix_insight: 'मोग्लिक्स इनसाइट',
    top: 'टॉप',
    price_range_of: 'की कीमत रेंज',
    categories_of: 'की श्रेणियां',
    in_price_range: 'की कीमत रेंज में',
    of_users_prefer: 'यूजर्स की पसंद',
    in_other_price_range: 'अन्य कीमत रेंज में',
    brands_of: 'ब्रांड्स ऑफ',
    of1: 'की',
    brand1: 'ब्रांड',
    of_other_brands: 'अन्य ब्रांडों के',
    of_users_buy: 'यूजर्स की खरीददारी',
    in: 'इसमें',
    shop_by: 'शॉप बाय',
    range: ' रेंज',
    are_you_looking_for: 'क्या आप ढूंढ रहे हैं',
    shop: 'शॉप',
    online: 'ऑनलाइन',
    pay_online_get_extra: 'ऑनलाइन भुगतान करें और अतिरिक्त प्राप्त करें',
    using: 'इस्तेमाल कर रहे हैं',
    wallets: 'यूपीआई, ईएमआई, क्रेडिट/डेबिट कार्ड, नेट बैंकिंग, वॉलेट',
    on_min_cart_value: 'न्यूनतम पर. की गाड़ी मूल्य',
    on: 'पर',
    moglix_offers_quality_genuine: 'मोग्लिक्स बेहतर गुणवत्ता और वास्तविक प्रदान करता है',
    from_renowned_brand: 'एक नामी ब्रांड से',
    brand_cat_heading: 'आसानी से हमारे वर्गीकरण के माध्यम से ब्राउज़ करें और मूल्य, विनिर्देशों, उपलब्धता और सौदों के बारे में अधिक जानकारी प्राप्त करें',
    brand_cat_desc: 'इन उत्पादों को सर्वोत्तम कीमतों पर खरीदें और उन्हें भारत भर में अपने दरवाजे पर वितरित करें।',
    home: 'होम',
    top_selling: 'टॉप सेलिंग',
    price_list_india: 'भारत में मूल्य सूची',
    latest_models: 'लेटेस्ट मॉडल्स',
    price: 'कीमत',
    discount: 'डिस्काउंट',
    data_last_updated_on: 'इस डेटा को आखिरी बार अपडेट किया गया था',
    genuine_products_from: 'से जेन्युइन प्रोडक्ट्स',
    at_the_best_price: 'मोग्लिक्स में ऑनलाइन सर्वश्रेष्ठ कीमतों पर',
    brand_desc: 'भारत और दुनिया भर के कई अन्य देशों में विश्वसनीय वितरकों और डीलरों के माध्यम से उत्पादों की खरीद की जाती है। हम, मोग्लिक्स में, अधिक से अधिक की पेशकश करते हैं',
    brand_desc2: 'जो हमारे ऑनलाइन स्टोर पर सूचीबद्ध हैं। ये विभिन्न उद्योगों, घरों, व्यवसायों और कार्यालयों में व्यक्तिगत या व्यावसायिक उपयोग के लिए उपयुक्त हैं। इन लिस्टिंग को विभिन्न उत्पाद श्रेणियों में ठीक से व्यवस्थित और व्यवस्थित किया गया है जैसे कि',
    brand_desc3: 'आसान नेविगेशन और निर्बाध उपयोगकर्ता अनुभव प्रदान करने के लिए।',
    brand_desc4: 'यदि आप सर्वश्रेष्ठ सौदों और ऑफ़र के लिए ऑनलाइन देख रहे हैं तो मोग्लिक्स एक स्टॉप समाधान है',
    brand_desc5: 'प्रोडक्ट्स। हम इन उत्पादों पर थोक खरीद या थोक कीमतों का विकल्प भी प्रदान करते हैं। दिल्ली एनसीआर, मुंबई, चेन्नई, बेंगलुरु, कोलकाता, चेन्नई, पुणे, जयपुर, हैदराबाद और अहमदाबाद जैसे प्रमुख शहरों सहित पूरे भारत में उपस्थिति होने के कारण, मोग्लिक्स देश भर में समय पर घर तक डिलीवरी प्रदान करता है।',
    products_by: 'द्वारा उत्पाद',
    popular_categories: 'लोकप्रिय कैटेगरीज',
    similar_category: 'इसी तरह की कैटेगरी',
    related_brands: 'संबंधित ब्रांड्स',
    related_category: 'संबंधित कैटेगरी',
    buy_online: 'सर्वोत्तम मूल्य पर उत्पाद ऑनलाइन',
    shop_online: 'सर्वोत्तम मूल्य पर उत्पाद ऑनलाइन',
    brand_title: 'मोगलिक्स में उत्पाद. भारत भर में मुफ्त वितरण और सीओडी विकल्प।',
    viewMore:"देखें और",
    select_language: 'भाषा चुनें',
    choose_right_for_you: 'अपने लिए सही ___name___ चुनें',
    save: 'बचत',
    instantly: 'तुरंत',
    with_online_payment: 'ऑनलाइन पेमेंट के साथ',
    via: 'वाया',
    payment_methods: 'यूपीआई, ईएमआई, क्रेडिट/डेबिट कार्ड, नेट बैंकिंग, वॉलेट',
    no_coupon_needed: 'कूपन की जरूरत नहीं',
    faq_category: '___category___ के बारे में अक्सर पूछे जाने वाले प्रश्न',
    categories: 'कैटेगरीज',
    view_all_products: 'सभी उत्पादों को देखें',
    view_all: 'सभी देखें',
    max_price: 'अधिकतम मूल्य',
    min_price: 'न्यूनतम मूल्य',
    price_range: 'प्राइस रेंज',
    quick_links: 'त्वरित सम्पक',
    shop_by_brand: 'ब्रांड द्वारा खरीदारी',
    best_sellers: 'बेस्टसेलर्स',
    articles_heading: 'संबंधित ___title___ लेख',
    mid_plp_heading: '___filter___ द्वारा खरीदारी करें',
    no_cost_emi_available: 'नो-कॉस्ट ईएमआई उपलब्ध है',
    similar_products_to_compare: 'समान प्रोडक्ट की तुलना करें',
    explore_from_top_brands: 'एक्सप्लोर करें ___category___ के टॉप ब्रांड्स',
    sub_categories: 'उपश्रेणियाँ',
    view_more: 'और देखें'
}  
