import CONSTANTS from "./constants";

export const product = {
    language: CONSTANTS.LANGUAGE_EN, // do not transalate this 
    search_bar_text: "Search Products/Categories",
    coupon_text: "EMIs Available on minimum  purchase of Rs. 3000 across banks and Rs. 4500 for Bajaj Finserv",
    cod_available:"COD Available",
    delivery_details:"Delivery Details",
    best_matching_heading:"Best Matching In-Stock Products",
    available_on_request:"Available on Request",
    consider_these_available_items:"Consider These Available Items",
    have_doubts_regarding_this_product:"Have doubts regarding this product",
    ask_now:"Ask Now",
    be_the_first_one_to_review:"Be the first one to provide review for this product",
    rating_review:"Review & Rating",
    product_videos:"Product Videos",
    read_more:"Read More",
    about_this_product:"About This Product",
    key_features:"Key Features",
    days_help_desk:"365 Days Help Desk",
    product_details:"Product Details",
    free_delivery:"Free Delivery",
    no_shipping_charge:"No shipping charge on this order",
    moglix_benefits:"Moglix Benefits",
    return_policy:"Return Policy",
    add_to_cart:"Add to Cart",
    buy_now:"Buy Now",
    more_from:"More from",
    use_code:"Use Code",
    best_of_moglix:"Best of Moglix",
    frequently_bought_together:"Frequently Bought Together",
    min_emi_text:"On min. purchase of Rs. 3000 across banks and Rs. 4500 for Bajaj Finserv",
    emi_gst_text_part1:"Get GST invoice and save up to",
    emi_gst_text_part2:"on business purchases",
    write_review:"Write a Review",
    recently_viewed:"Recently Viewed",
    view_more_faq:"VIEW MORE FAQs",
    show_all_key_features:"Show All Key Features",
    buy_it_again:"Buy It Again",
    brand_store:"Brand Store",
    interested_to_buy_in_bulk:"Interested to buy in bulk?",
    get_quote:"GET QUOTE",
    incl_of_taxes:"Incl. of all taxes",
    get_customized_price:"Get customized price",
    slide_to_request:"SLIDE TO RAISE REQUEST",
    open_app:"Open App",
    enter_your_pincode:"Enter your pincode",
    check_serviceability:"Check serviceability at your location",
    gst:"GST",
    off:"OFF",
    reviews:"Reviews",
    offers_coupons:"Offers and Coupons",
    emi_available:"EMI's Available"
}
  