import CONSTANTS from "./constants";

export const product = {
    language: CONSTANTS.LANGUAGE_HI, // do not transalate this 
    search_bar_text: "सर्च प्रोडक्ट्स/ कैटेगरीज",
    coupon_text: "EMI बैंकों में न्यूनतम रु. 3000 और बजाज फिनसर्व में रु. 4500 की खरीद पर उपलब्ध है",
    cod_available:"कैश ऑन डिलीवरी उपलब्ध",
    delivery_details:"डिलिवरी डिटेल्स",
    best_matching_heading:"बेस्ट मैचिंग इन-स्टॉक प्रोडक्ट्स",
    available_on_request:"रिक्वेस्ट पर उपलब्ध",
    consider_these_available_items:"इन उपलब्ध प्रोडक्ट पर विचार करें",
    have_doubts_regarding_this_product:"विशिष्ट जानकारी खोज रहे हैं",
    ask_now:"सवाल पूछें",
    be_the_first_one_to_review:"इस प्रोडक्ट के लिए समीक्षा प्रदान करने वाले पहले व्यक्ति बनें",
    rating_review:"समीक्षा और रेटिंग",
    product_videos:"प्रोडक्ट वीडियो",
    read_more:"और पढ़ें",
    about_this_product:"इस प्रोडक्ट के बारे में",
    key_features:"प्रमुख विशेषताएं",
    days_help_desk:"365 दिन हैल्प डेस्क",
    product_details:"प्रोडक्ट विवरण",
    free_delivery:"फ्री डिलिवरी",
    no_shipping_charge:"इस आर्डर पर कोई शिपिंग शुल्क नहीं",
    moglix_benefits:"मोगलिक्स के फायदे",
    return_policy:"रिटर्न पॉलिसी",
    add_to_cart:"कार्ट में डालें",
    buy_now:"अभी खरीदें",
    more_from:"एक्सप्लोर करें दूसरे ___categoryName___",
    more_from_brand:"एक्सप्लोर करें दूसरे ___brandName___ ___categoryName___",
    use_code:"कोड का इस्तेमाल करें",
    best_of_moglix:"मोगलिक्स का बेस्ट",
    frequently_bought_together:"इस प्रोडक्ट  को खरीदने वाले ग्राहकों ने ये भी खरीदा है",
    min_emi_text:"EMI बैंकों में न्यूनतम रु. 3000 और बजाज फिनसर्व में रु. 4500 की खरीद पर उपलब्ध है",
    emi_gst_text_part1:"जीएसटी चालान प्राप्त करें और व्यापार खरीद पर",
    emi_gst_text_part2:"तक की बचत करें।",
    write_review:"समीक्षा लिखें",
    recently_viewed:"हाल ही में देखे गए प्रोडक्ट",
    view_more_faq:"अधिक बार पूछे जाने वाले प्रश्न देखें",
    show_all_key_features:"सभी प्रमुख विशेषताएं दिखाएं",
    show_all_specifination: "सभी स्पेसिफिकेशंस दिखाएं",
    free_details:"",
    buy_it_again:"फिर से खरीदें",
    interested_to_buy_in_bulk:"थोक में खरीदारी के इच्छुक?",
    get_customized_price:"कस्टमाइज़्ड प्राइस पाएं",
    get_quote:"कोटेशन प्राप्त करें",
    incl_of_taxes:"सभी टैक्स सहित",
    slide_to_request:"कोटेशन रिक्वेस्ट करने के लिए स्लाइड करें",
    open_app:"ऐप खोलें",
    enter_your_pincode:"अपना पिनकोड दर्ज करें",
    check_serviceability:"अपने स्थान पर सेवा की योग्यता की जांच करें",
    gst:"जीएसटी",
    off:"छूट",
    reviews:"समीक्षा",
    offers_coupons:"ऑफर्स और कूपन्स",
    emi_available:"ईएमआई उपलब्ध",
    brand:"ब्रांड",
    brand_store:"ब्रांड स्टोर",
    ratings_and:"रेटिंग और",
    reviews_small:"समीक्षा",
    avg_rating_based_on:"रेटिंग औसत के आधार पर",
    verified_purchase:"वेरिफ़ाई की गई खरीद",
    view:"देखें",
    check:"चेक करें",
    gst_invoice:"जीएसटी चालान ",
    available:"उपलब्ध",
    secure:"सुरक्षित",
    payments:"भुगतान",
    days_365:"365 दिन",
    help_desk:" हैल्प डेस्क",
    upto_7days:"___number___ दिनों तक",
    returnable:"वापसी योग्य",
    wrong:"गलत",
    product:"प्रोडक्ट",
    damaged:"डैमेज हुआ",
    defective:"दोषपूर्ण",
    download_moglix_app:"मोग्लिक्स ऐप डाउनलोड करें",
    get_100_off:"Rs100 की छूट",
    on_your_first_order:" अपने पहले ऑर्डर पर",
    similar_products:"मिलते-जुलते प्रोडक्ट",
    buy_more_save_more:"अधिक खरीदें और अधिक बचत करें",
    buy_more:"अधिक खरीदें",
    frequently_asked_questions:"अक्सर पूछे जाने वाले सवाल",
    customer_reviews:"ग्राहक समीक्षा",
    displaying_questions:"प्रदर्शन कर रहे हैं सवाल",
    more_helpful_review:"अधिक उपयोगी समीक्षा",
    explore_now:"अभी एक्सप्लोर करें",
    get_best_price:"बेस्ट प्राइस पाएं",
    store:"स्टोर",
    product_specifications:"प्रोडक्ट स्पेसिफिकेशंस",
    available_coupons:"उपलब्ध कूपन",
    and_get:"और प्राप्त करें",
    //product info key
    "specifications":"स्पेसिफिकेशंस",
    "images":"तस्वीरें",
    "product details":"प्रोडक्ट विवरण",
    "key features": 'प्रमुख विशेषताएं',
    "videos": 'वीडियो',
    invalid_pincode_validation:"गलत पिनकोड दिया गया",
    prepaid_payment_only:"केवल प्रीपेड भुगतान उपलब्ध है",
    accordian_list1_label: 'संबंधित प्रोडक्ट खोजें',
    accordian_list2_label: 'लोकप्रिय ब्रांड कैटेगरी',
    accordian_list3_label: 'संबंधित प्रोडक्ट की खरीदारी करें',
    slide_to_raise_request:'कोटेशन रिक्वेस्ट करने के लिए स्लाइड करें',
    // we_will_get_in_touch:"We will get in touch with you on",
    successfully_added_to_wishlist:"इच्छा सूची में सफलतापूर्वक जोड़ा गया",
    view_in_stock:"इन-स्टॉक देखें",
    pincode_shipping_applicable: 'शिपिंग लागू',
    pincode_on_this_order: 'इस आर्डर पर',
    pincode_delivery_text: 'वितरण ___deliveryDays___ में ___pincode___ पर उपलब्ध है',
    pincode_delivery_unavalible: '___pincode___ में डिलीवरी अनुपलब्ध है',
    pincode_pay_at_time_delivery: 'आप डिलीवरी के समय भुगतान कर सकते हैं',
    coupon_static_text:'भुगतान ऑनलाइन करें और ___brandName ___ ___categoryName___ पर ___coupon_discount___ की छूट प्राप्त करें।',
    requested_successfully:"रिक्वेस्ट सफल",
    coupon_text1:"भुगतान ऑनलाइन करें और ___discount___ की छूट प्राप्त करें।",
    looking_for_category:"क्या आप ___categoryName___ की तलाश कर रहे हैं",
    min_cart_value: '___count___ रुपये के न्यूनतम कार्ट मूल्य पर',
    see_more_coupons: '___promoCodes___ और कूपन देखें',
    prepaid_discount_text: `ऑनलाइन भुगतान करें और प्राप्त करें, 
    ___brandName___ ___categoryName___ में ___minimumCartValue___ के न्यूनतम मूल्य पर यूपीआई, ईएमआई, क्रेडिट / डेबिट कार्ड, नेट बैंकिंग, वॉलेट का उपयोग करके भुगतान करते समय लागू`,
    get_rfq_text_1: 'बड़ी मात्रा में सामान खरीदें',
    get_rfq_text_2: 'अपने व्यवसाय के लिए सर्वोत्तम मूल्य प्राप्त करें',
    get_rfq_text_3: 'हम आपसे संपर्क करेंगे : ',
    get_rfq_text_4: 'शुक्रिया! हमारा समर्थन सदस्य 24 घंटे के भीतर आपसे संपर्क करेगा।',
    show_more: 'और दिखाएं',
    show_less: 'कम दिखाएं',
    of:'/',
    emis_availaible:'उपलब्ध EMIs:',
    brand_store_text:"___brand___ स्टोर",
    missing: 'Missing'
}  
