import { CommonModule } from "@angular/common";
import { Component, Input, NgModule, OnInit } from "@angular/core";
import { ProductCardVerticalGridViewModule } from "@app/modules/product-card/product-card-vertical-grid-view/product-card-vertical-grid-view.module";
import { ProductCardVerticalContainerModule } from "@app/modules/ui/product-card-vertical-container/product-card-vertical-container.module";
import { ProductCardFeature } from "@app/utils/models/product.listing.search";
import { ProductService } from "@app/utils/services/product.service";

@Component({
  selector: "shop-by-brands",
  templateUrl: "./shop-by-brands.component.html",
  styleUrls: ["./shop-by-brands.component.scss"],
})
export class ShopByBrandsComponent implements OnInit {
  @Input("data") data: any = {
    CRI: [
      {
        moglixPartNumber: "MSNG9VNPQ1Q6KP",
        moglixProductNo: null,
        mrp: 17895.0,
        salesPrice: 11799.0,
        priceRange: null,
        priceWithoutTax: 9999.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "Cri 1hp 10 Stage Single Phase Submersible Pump With Digital Control Starter",
        productName:
          "CRI 1HP 10 Stage Single Phase Submersible Pump with Digital Control Starter",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: CRI",
        brandName: "Cri",
        brandId: "86735a5c-5a4f-4792-8786-f44dd4b2b00b",
        quantityAvailable: 6,
        moq: 1,
        mainImagePath: "p/YwDyvFWpKlfHR-xxlarge.jpg",
        moglixImageNumber: "YwDyvFWpKlfHR",
        mainImageLink: "p/YwDyvFWpKlfHR-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 34.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [
          {
            link: "https://www.youtube.com/embed/uNl6gyAK9Vg",
            title:
              "CRI 1HP 10 Stage Single Phase Submersible Pump with Digital Control Starter",
            uploadedBy: null,
            description:
              "Experience the ultimate water pumping solution with the CRI 1HP 10 Stage Single Phase Submersible Pump with Digital Control Starter. This high-performance pump combines cutting-edge technology with efficient functionality, ensuring smooth operations and hassle-free maintenance. With its 10-stage design, it delivers exceptional water pressure, making it perfect for various applications. Stay in control with the digital control starter, allowing you to effortlessly manage the pump's performance and customize settings. Don't miss out on this incredible pump that will revolutionize your water pumping experience. #CRI #SubmersiblePump #DigitalControl #HighPerformance",
            publishedDate: "May 30, 2023 12:00:00 AM",
          },
        ],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 10,
        reviewCount: 10,
        avgRating: 4.7,
      },
      {
        moglixPartNumber: "MSNNKQGNMX3Z9X",
        moglixProductNo: null,
        mrp: 17895.0,
        salesPrice: 14999.0,
        priceRange: null,
        priceWithoutTax: 12711.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "Cri 1hp 10 Stage Oil Filled Submersible Pump With Digital Control Panel & 50m Cable",
        productName:
          "CRI 1HP 10 Stage Oil Filled Submersible Pump with Digital Control Panel & 50m Cable",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: CRI",
        brandName: "Cri",
        brandId: "86735a5c-5a4f-4792-8786-f44dd4b2b00b",
        quantityAvailable: 9,
        moq: 1,
        mainImagePath: "p/Oi6uSoVCV1xCj-xxlarge.jpg",
        moglixImageNumber: "Oi6uSoVCV1xCj",
        mainImageLink: "p/Oi6uSoVCV1xCj-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 16.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
      {
        moglixPartNumber: "MSN4K6Z72XE8KQ",
        moglixProductNo: null,
        mrp: 17895.0,
        salesPrice: 15199.0,
        priceRange: null,
        priceWithoutTax: 12880.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "Cri 1hp 10 Stage Oil Filled Submersible Pump With Digital Control Panel & 40m Cable",
        productName:
          "CRI 1HP 10 Stage Oil Filled Submersible Pump with Digital Control Panel & 40m Cable",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: CRI",
        brandName: "Cri",
        brandId: "86735a5c-5a4f-4792-8786-f44dd4b2b00b",
        quantityAvailable: 10,
        moq: 1,
        mainImagePath: "p/DyIVu3VaZbRyZ-xxlarge.jpg",
        moglixImageNumber: "DyIVu3VaZbRyZ",
        mainImageLink: "p/DyIVu3VaZbRyZ-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 15.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
      {
        moglixPartNumber: "MSN19Z20NZ4353",
        moglixProductNo: null,
        mrp: 17895.0,
        salesPrice: 14399.0,
        priceRange: null,
        priceWithoutTax: 12202.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "Cri 1hp 10 Stage Water Filled Single Phase Submersible Pump With Digital Control Starter",
        productName:
          "CRI 1HP 10 Stage Water Filled Single Phase Submersible Pump with Digital Control Starter",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: CRI",
        brandName: "Cri",
        brandId: "86735a5c-5a4f-4792-8786-f44dd4b2b00b",
        quantityAvailable: 10,
        moq: 1,
        mainImagePath: "p/znMu7c7wuIjVC-xxlarge.jpg",
        moglixImageNumber: "znMu7c7wuIjVC",
        mainImageLink: "p/znMu7c7wuIjVC-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 19.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
      {
        moglixPartNumber: "MSN4K6Z72X28KQ",
        moglixProductNo: null,
        mrp: 17895.0,
        salesPrice: 14799.0,
        priceRange: null,
        priceWithoutTax: 12541.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "Cri 1hp 10 Stage Oil Filled Submersible Pump With Digital Control Panel & 30m Cable",
        productName:
          "CRI 1HP 10 Stage Oil Filled Submersible Pump with Digital Control Panel & 30m Cable",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: CRI",
        brandName: "Cri",
        brandId: "86735a5c-5a4f-4792-8786-f44dd4b2b00b",
        quantityAvailable: 10,
        moq: 1,
        mainImagePath: "p/Ky42IutnqwXwt-xxlarge.jpg",
        moglixImageNumber: "Ky42IutnqwXwt",
        mainImageLink: "p/Ky42IutnqwXwt-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 17.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
      {
        moglixPartNumber: "MSNE9J8G28WR9D",
        moglixProductNo: null,
        mrp: 11639.0,
        salesPrice: 10599.0,
        priceRange: null,
        priceWithoutTax: 8982.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "Cri Dino So100 1hp Single Phase Horizontal Openwell Submersible Water Pump With Control Panel",
        productName:
          "CRI Dino SO100 1HP Single Phase Horizontal Openwell Submersible Water Pump with Control Panel",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: CRI",
        brandName: "Cri",
        brandId: "86735a5c-5a4f-4792-8786-f44dd4b2b00b",
        quantityAvailable: 0,
        moq: 1,
        mainImagePath: "p/yBhMFZIUZXdNp-xxlarge.jpg",
        moglixImageNumber: "yBhMFZIUZXdNp",
        mainImageLink: "p/yBhMFZIUZXdNp-large.jpg",
        mainImageAltTag: null,
        keyFeatures: [
          "Anti-Corrosive Stainless Steel Motor Body",
          "Enhanced Motor Design Ensures the Higher Cooling Effect",
          "High Operating Efficiency Resulting in Low Power Consumption",
          "Optimized Hydraulic Design for Efficient Performance",
          "Specially Designed Thrust Bearing to Withstand High Axial Load",
          "T-Bolt Design Motor Ensures Rigid Construction",
          "Smooth Surface Finish Results Friction Free Flow of Fluid",
          "Designed for Wide Voltage Applications",
          "Ss 304 Grade Stainless Steel Stage Casings & Impellers in Radial Flow Series",
          "SS 410 Impeller/ Bronze Impeller Available in Mixed Flow Series",
        ],
        discount: 8.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
    ],
    "V-Guard": [
      {
        moglixPartNumber: "MSN457MWJN3N9J",
        moglixProductNo: null,
        mrp: 15290.0,
        salesPrice: 12799.0,
        priceRange: null,
        priceWithoutTax: 10846.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "V Guard Vof110 1hp Iron Single Phase 10 Stage Submersible Pump With Digital Control Panel",
        productName:
          "V Guard VOF110 1HP Iron Single Phase 10 Stage Submersible Pump with Digital Control Panel",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V-Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 10,
        moq: 1,
        mainImagePath: "p/jT35nqJ7u8K9F-xxlarge.jpg",
        moglixImageNumber: "jT35nqJ7u8K9F",
        mainImageLink: "p/jT35nqJ7u8K9F-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 16.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 5,
        reviewCount: 5,
        avgRating: 4.6,
      },
      {
        moglixPartNumber: "MSN2KM1P2NPX9V",
        moglixProductNo: null,
        mrp: 15880.0,
        salesPrice: 9759.0,
        priceRange: null,
        priceWithoutTax: 8270.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "V Guard 1hp Single Phase Openwell Submersible Pump With Starter & Accessories Vosk-f90",
        productName:
          "V Guard 1HP Single Phase Openwell Submersible Pump with Starter & Accessories VOSK-F90",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 2,
        moq: 1,
        mainImagePath: "p/UeOWOUI7inU4E-xxlarge.jpg",
        moglixImageNumber: "UeOWOUI7inU4E",
        mainImageLink: "p/UeOWOUI7inU4E-large.jpg",
        mainImageAltTag: null,
        keyFeatures: [
          "Smooth & Silent Operation",
          "Rust Preventive & Easy to Maintain",
          "Stainless Steel Hardware Sturdy Built, Low Energy Consumption, Lightweight & Compact",
        ],
        discount: 38.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 7,
        reviewCount: 7,
        avgRating: 4.72,
      },
      {
        moglixPartNumber: "MSN39YRPQDQ25Q",
        moglixProductNo: null,
        mrp: 18000.0,
        salesPrice: 14399.0,
        priceRange: null,
        priceWithoutTax: 12202.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "V Guard Nova-ot1512 1.5hp Stainless Steel 12 Stage Single Phase Submersible Pump",
        productName:
          "V Guard NOVA-OT1512 1.5HP Stainless Steel 12 Stage Single Phase Submersible Pump",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V-Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 9,
        moq: 1,
        mainImagePath: "p/ki9YuDVwnW1QN-xxlarge.jpg",
        moglixImageNumber: "ki9YuDVwnW1QN",
        mainImageLink: "p/ki9YuDVwnW1QN-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 20.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "1.1 kW",
          Phase: "Single Phase",
          "Motor Power": "1.5 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
      {
        moglixPartNumber: "MSNE9J8XERE09D",
        moglixProductNo: null,
        mrp: 20350.0,
        salesPrice: 16209.0,
        priceRange: null,
        priceWithoutTax: 13736.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "V Guard Vwf1512 1.5hp Stainless Steel Single Phase Submersible Pump With Digital Control Panel",
        productName:
          "V Guard VWF1512 1.5HP Stainless Steel Single Phase Submersible Pump with Digital Control Panel",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V-Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 9,
        moq: 1,
        mainImagePath: "p/HPK5qJZHScO5V-xxlarge.jpg",
        moglixImageNumber: "HPK5qJZHScO5V",
        mainImageLink: "p/HPK5qJZHScO5V-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 19.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "1.1 kW",
          Phase: "Single Phase",
          "Motor Power": "1.5 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 5,
        reviewCount: 5,
        avgRating: 4.6,
      },
      {
        moglixPartNumber: "MSNPKEP3JOJQ9G",
        moglixProductNo: null,
        mrp: 18975.0,
        salesPrice: 13249.0,
        priceRange: null,
        priceWithoutTax: 11227.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "V Guard Nova- Ot0110 1hp Stainless Steel Single Phase Submersible Pump With Digital Control Panel & 30m Cable",
        productName:
          "V Guard NOVA- OT0110 1HP Stainless Steel Single Phase Submersible Pump with Digital Control Panel & 30m Cable",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V-Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 11,
        moq: 1,
        mainImagePath: "p/CenlrywPvCstp-xxlarge.jpg",
        moglixImageNumber: "CenlrywPvCstp",
        mainImageLink: "p/CenlrywPvCstp-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 30.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 0,
        reviewCount: 0,
        avgRating: 0.0,
      },
      {
        moglixPartNumber: "MSNNKQGNMXMZ9X",
        moglixProductNo: null,
        mrp: 14444.0,
        salesPrice: 11699.0,
        priceRange: null,
        priceWithoutTax: 9914.0,
        manufacturerName: null,
        itemCode: null,
        variantName:
          "V Guard Nova-ot0108 1hp Stainless Steel Single Phase Submersible Pump With Digital Control Panel",
        productName:
          "V Guard NOVA-OT0108 1HP Stainless Steel Single Phase Submersible Pump with Digital Control Panel",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V-Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 10,
        moq: 1,
        mainImagePath: "p/BFuStyOTLZ1bP-xxlarge.jpg",
        moglixImageNumber: "BFuStyOTLZ1bP",
        mainImageLink: "p/BFuStyOTLZ1bP-large.jpg",
        mainImageAltTag: null,
        keyFeatures: null,
        discount: 19.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          "Power Rating": "0.75 kW",
          Phase: "Single Phase",
          "Motor Power": "1 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 5,
        reviewCount: 5,
        avgRating: 4.6,
      },
      {
        moglixPartNumber: "MSNZ526NOQJM9X",
        moglixProductNo: null,
        mrp: 9000.0,
        salesPrice: 7459.0,
        priceRange: null,
        priceWithoutTax: 6321.186440677967,
        manufacturerName: null,
        itemCode: "VOWS05",
        variantName:
          "V Guard 0.5hp Single Phase Openwell Submersible Pump With Starter & Accessories, Nova-ossh60 Vows05",
        productName:
          "V Guard 0.5HP Single Phase Openwell Submersible Pump with Starter & Accessories, Nova-OSSH60 VOWS05",
        taxonomy: null,
        productUrl: null,
        shortDesc: "Brand: V Guard",
        brandName: "V-guard",
        brandId: "3f7036fd-7630-4156-9033-627daae6879f",
        quantityAvailable: 25,
        moq: 1,
        mainImagePath: "p/cN14ulQ3Cvhdi-xxlarge.jpg",
        moglixImageNumber: "cN14ulQ3Cvhdi",
        mainImageLink: "p/cN14ulQ3Cvhdi-large.jpg",
        mainImageAltTag: null,
        keyFeatures: [
          "Comes Along  with Accessories",
          "Rust Preventive & Easy to Maintain",
          "Stainless Steel Hardware Sturdy Built, Low Energy Consumption & Lightweight & Compact",
        ],
        discount: 24.0,
        quantityUom: null,
        categoryCodes: ["128111200"],
        rating: null,
        productTags: [],
        filterableAttributes: {
          Phase: "Single Phase",
          "Motor Power": "0.5 HP",
        },
        attributeValuesForPart: null,
        videoInfo: [],
        attributeToCompare: null,
        itemInPack: "1 Piece",
        ratingCount: 10,
        reviewCount: 10,
        avgRating: 4.4,
      },
    ],
  };

  readonly cardFeaturesConfig: ProductCardFeature = {
    // feature config
    enableAddToCart: false,
    enableBuyNow: false,
    enableFullAddToCart: true,
    enableFeatures: false,
    enableRating: true,
    enableVideo: false,
    // design config
    enableCard: true,
    verticalOrientation: true,
    horizontalOrientation: false,
    lazyLoadImage: true,
  };

  tabsArray: { id: number; name: string; data: any[]; isSelected: boolean }[] =
    [];

  constructor(private _productService: ProductService) {}

  ngOnInit(): void {
    console.log(" i m in");
    let count = 0;
    for (const i in this.data) {
      console.log("DAta ====>", this.data[i]);
      count += 1;
      this.tabsArray.push({
        id: count,
        name: i,
        data:
          (this.data[i] as any[])
            .map((item) =>
              this._productService.recentProductResponseToProductEntityV1(item)
            )
            .filter((res) => this._productService.isInStock(res) == true) || [],
        isSelected: false,
      });
    }
    if (this.tabsArray.length > 0) {
      this.tabsArray[0].isSelected = true;
    }
  }

  setProductTab(tabName) {
    this.tabsArray.forEach((element, index) => {
      this.tabsArray[index].isSelected = false;
    });
    this.tabsArray.forEach((element, index) => {
      if (this.tabsArray[index].id == tabName) {
        this.tabsArray[index].isSelected = true;
      }
    });
  }
}

@NgModule({
  declarations: [ShopByBrandsComponent],
  imports: [
    CommonModule,
    ProductCardVerticalContainerModule,
    ProductCardVerticalGridViewModule,
  ],
  exports: [ShopByBrandsComponent],
})
export class ShopByBrandsModule {}
