export const DATA_NB_RAZ = {"CC":
{"amex debit card":{
    "id":9,"idList":[],
    "name":"amex debit card",
    "code":"AMEX","enable":true,
    "platformCode":null,"mode":"CC",
    "topBank":false,
    "attributeNames":{
        "country":false,
        "firstname":true,
        "address2":false,
        "city":false,
        "address1":false,
        "ccnum":true,
        "ccexpmon":true,"ccvv":true,"lastname":false,"zipcode":false,"phone":true,"additional_charges":false,"ccexpyr":true,"state":false,"productinfo":true,"ccname":true,"email":true,"bankcode":true},"attributeValueMap":{}},"dinersclub debit card":{"id":10,"idList":[],"name":"dinersclub debit card","code":"DINR","enable":true,"platformCode":null,"mode":"CC","topBank":false,"attributeNames":{"country":false,"firstname":true,"address2":false,"city":false,"address1":false,"ccnum":true,"ccexpmon":true,"ccvv":true,"lastname":false,"zipcode":false,"phone":true,"additional_charges":false,"ccexpyr":true,"state":false,"productinfo":true,"ccname":true,"email":true,"bankcode":true},"attributeValueMap":{}},"mastercard debit card":{"id":8,"idList":[],"name":"mastercard debit card","code":"MAST","enable":true,"platformCode":null,"mode":"CC","topBank":false,"attributeNames":{"country":false,"firstname":true,"address2":false,"city":false,"address1":false,"ccnum":true,"ccexpmon":true,"ccvv":true,"lastname":false,"zipcode":false,"phone":true,"additional_charges":false,"ccexpyr":true,"state":false,"productinfo":true,"ccname":true,"email":true,"bankcode":true},"attributeValueMap":{}}},"EMI":{"emi":{"id":14,"idList":[],"name":"emi","code":"EMI","enable":true,"platformCode":null,"mode":"EMI","topBank":false,"attributeNames":{"country":false,"firstname":true,"address2":false,"city":false,"address1":false,"ccnum":true,"ccexpmon":true,"ccvv":true,"lastname":false,"zipcode":false,"phone":true,"additional_charges":false,"ccexpyr":true,"state":false,"productinfo":true,"ccname":true,"email":true,"bankcode":true},"attributeValueMap":{}}},"NEFT":{"neft":{"id":4,"idList":[],"name":"neft","code":"NEFT","enable":true,"platformCode":null,"mode":"NEFT","topBank":false,"attributeNames":{"email":true},"attributeValueMap":{}}},
        "NB":{
            "Airtel Payments Bank":{
                "id":71,
                "idList":[],
                "name":"Airtel Payments Bank",
                "code":"AIRP",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Allahabad Bank":{
                "id":72,
                "idList":[],
                "name":"Allahabad Bank",
                "code":"AIRP",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Andhra Bank":{
                "id":73,
                "idList":[],
                "name":"Andhra Bank",
                "code":"ANDB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Bank of Bahrein and Kuwait":{
                "id":75,
                "idList":[],
                "name":"Andhra Bank",
                "code":"BBKM",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Bank of Baroda - Retail Banking":{
                "id":76,
                "idList":[],
                "name":"Andhra Bank",
                "code":"BARB_R",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },  		
            "Bank of India":{
                "id":77,
                "idList":[],
                "name":"Andhra Bank",
                "code":"BKID",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },		
            "Bank of Maharashtra":{
                "id":78,
                "idList":[],
                "name":"Andhra Bank",
                "code":"MAHB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },		
            "Canara Bank":{
                "id":79,
                "idList":[],
                "name":"Andhra Bank",
                "code":"CNRB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Catholic Syrian Bank":{
                "id":80,
                "idList":[],
                "name":"Catholic Syrian Bank",
                "code":"CSBK",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },		
            "Central Bank of India":{
                "id":81,
                "idList":[],
                "name":"Catholic Syrian Bank",
                "code":"CBIN",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },		
            "City Union Bank":{
                "id":82,
                "idList":[],
                "name":"Catholic Syrian Bank",
                "code":"CIUB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Corporation Bank":{
                "id":83,
                "idList":[],
                "name":"Catholic Syrian Bank",
                "code":"CORP",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },		
            "Cosmos Co-operative Bank":{
                "id":84,
                "idList":[],
                "name":"Catholic Syrian Bank",
                "code":"COSB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },			
            "DCB Bank":{
                "id":85,
                "idList":[],
                "name":"DCB Bank",
                "code":"DCBL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Dena Bank":{
                "id":86,
                "idList":[],
                "name":"Dena Bank",
                "code":"BKDN",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Deutsche Bank":{
                "id":87,
                "idList":[],
                "name":"Deutsche Bank",
                "code":"DEUT",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Development Bank of Singapore":{
                "id":88,
                "idList":[],
                "name":"Development Bank of Singapore",
                "code":"DBSS",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Dhanlaxmi Bank":{
                "id":89,
                "idList":[],
                "name":"Dhanlaxmi Bank",
                "code":"DLXB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Equitas Small Finance Bank":{
                "id":90,
                "idList":[],
                "name":"Equitas Small Finance Bank",
                "code":"ESFB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Federal Bank":{
                "id":91,
                "idList":[],
                "name":"Federal Bank",
                "code":"FDRL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "IDBI":{
                "id":94,
                "idList":[],
                "name":"IDBI",
                "code":"FDRL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "IDFC Bank":{
                "id":95,
                "idList":[],
                "name":"IDFC Bank",
                "code":"IDFB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Indian Bank":{
                "id":96,
                "idList":[],
                "name":"Indian Bank",
                "code":"IDIB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Indian Overseas Bank":{
                "id":97,
                "idList":[],
                "name":"Indian Overseas Bank",
                "code":"IOBA",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Indusind Bank":{
                "id":98,
                "idList":[],
                "name":"Indusind Bank",
                "code":"INDB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Jammu and Kashmir Bank":{
                "id":99,
                "idList":[],
                "name":"Jammu and Kashmir Bank",
                "code":"JAKA",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Janata Sahakari Bank (Pune)":{
                "id":100,
                "idList":[],
                "name":"Janata Sahakari Bank (Pune)",
                "code":"JSBP",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Karnataka Bank":{
                "id":101,
                "idList":[],
                "name":"Karnataka Bank",
                "code":"KARB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Karur Vysya Bank":{
                "id":102,
                "idList":[],
                "name":"Karur Vysya Bank",
                "code":"KVBL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Kotak Mahindra Bank":{
                "id":103,
                "idList":[],
                "name":"Kotak Mahindra Bank",
                "code":"KKBK",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Lakshmi Vilas Bank - Corporate Banking":{
                "id":104,
                "idList":[],
                "name":"Lakshmi Vilas Bank - Corporate Banking",
                "code":"LAVB_C",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Lakshmi Vilas Bank - Retail Banking":{
                "id":105,
                "idList":[],
                "name":"Lakshmi Vilas Bank - Corporate Banking",
                "code":"LAVB_R",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "NKGSB Co-operative Bank":{
                "id":106,
                "idList":[],
                "name":"NKGSB Co-operative Bank",
                "code":"NKGS",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Oriental Bank of Commerce":{
                "id":107,
                "idList":[],
                "name":"Oriental Bank of Commerce",
                "code":"ORBC",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Punjab & Maharashtra Co-operative Bank":{
                "id":108,
                "idList":[],
                "name":"Punjab & Maharashtra Co-operative Bank",
                "code":"PMCB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Punjab & Sind Bank":{
                "id":109,
                "idList":[],
                "name":"Punjab & Sind Bank",
                "code":"PSIB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Punjab National Bank - Retail Banking":{
                "id":110,
                "idList":[],
                "name":"Punjab National Bank - Retail Banking",
                "code":"PUNB_R",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "RBL Bank":{
                "id":111,
                "idList":[],
                "name":"RBL Bank",
                "code":"RATN",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Saraswat Co-operative Bank":{
                "id":112,
                "idList":[],
                "name":"Saraswat Co-operative Bank",
                "code":"SRCB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Shamrao Vithal Co-operative Bank":{
                "id":113,
                "idList":[],
                "name":"Shamrao Vithal Co-operative Bank",
                "code":"SVCB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "South Indian Bank":{
                "id":114,
                "idList":[],
                "name":"South Indian Bank",
                "code":"SIBL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "State Bank of Bikaner and Jaipur":{
                "id":116,
                "idList":[],
                "name":"State Bank of Bikaner and Jaipur",
                "code":"SBBJ",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "State Bank of Hyderabad":{
                "id":117,
                "idList":[],
                "name":"State Bank of Hyderabad",
                "code":"SBHY",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "State Bank of Mysore":{
                "id":119,
                "idList":[],
                "name":"State Bank of Mysore",
                "code":"SBMY",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "State Bank of Patiala":{
                "id":120,
                "idList":[],
                "name":"State Bank of Patiala",
                "code":"STBP",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "State Bank of Travancore":{
                "id":121,
                "idList":[],
                "name":"State Bank of Travancore",
                "code":"SBTR",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Syndicate Bank":{
                "id":122,
                "idList":[],
                "name":"Syndicate Bank",
                "code":"SYNB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Tamilnadu Mercantile Bank":{
                "id":123,
                "idList":[],
                "name":"Tamilnadu Mercantile Bank",
                "code":"TMBL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Tamilnadu State Apex Co-operative Bank":{
                "id":124,
                "idList":[],
                "name":"Tamilnadu State Apex Co-operative Bank",
                "code":"TNSC",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "UCO Bank":{
                "id":125,
                "idList":[],
                "name":"UCO Bank",
                "code":"UCBA",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Union Bank of India":{
                "id":126,
                "idList":[],
                "name":"Union Bank of India",
                "code":"UBIN",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Vijaya Bank":{
                "id":128,
                "idList":[],
                "name":"Vijaya Bank",
                "code":"VIJB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Yes Bank":{
                "id":129,
                "idList":[],
                "name":"Yes Bank",
                "code":"YESB",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":false,
                "attributeNames":{},
                "attributeValueMap":{}
            }
        },
        "NB-top":{"State Bank of India":{
                "id":118,"idList":[],
                "paymentId": 118,
                "name":"state bank of india",
                "code":"SBIN",
                "enable":true,"platformCode":null,"mode":"NB","topBank":true,"attributeNames":{},"attributeValueMap":{}
            },
            "United Bank of India":{
                "id":127,
                "idList":[],
                "name":"United Bank of India",
                "code":"UTBI",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":true,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "Standard Chartered Bank":{
                "id":115,
                "idList":[],
                "name":"Standard Chartered Bank",
                "code":"SCBL",
                "enable":true,
                "platformCode":null,
                "mode":"NB",
                "topBank":true,
                "attributeNames":{},
                "attributeValueMap":{}
            },
            "AXIS Bank NetBanking":{
                "id":74,
                "idList":[],
                "paymentId": 74,
                "name":"axis bank netbanking","code":"UTIB","enable":true,"platformCode":null,"mode":"NB","topBank":true,"attributeNames":{},"attributeValueMap":{}
        },"HDFC Bank":{"id":92,"idList":[],"name":"hdfc bank","code":"HDFC","enable":true,"platformCode":null,"mode":"NB","topBank":true,"attributeNames":{},"attributeValueMap":{}},
        "ICICI Netbanking":{"id":93,"idList":[],"name":"icici netbanking","code":"ICIC","enable":true,"platformCode":null,"mode":"NB","topBank":true,"attributeNames":{},"attributeValueMap":{}}},
        "DC":{"visa debit card":{"id":6,"idList":[],"name":"visa debit card","code":"MAESTRO CARD","enable":false,"platformCode":null,"mode":"DC","topBank":false,"attributeNames":{"country":false,"firstname":true,"address2":false,"city":false,"address1":false,"ccnum":true,"ccexpmon":true,"ccvv":true,"lastname":false,"zipcode":false,"phone":true,"additional_charges":false,"ccexpyr":true,"state":false,"productinfo":true,"ccname":true,"email":true,"bankcode":true},"attributeValueMap":{}},"maestro debit card":{"id":7,"idList":[],"name":"maestro debit card","code":"SMAE","enable":true,"platformCode":null,"mode":"DC","topBank":false,"attributeNames":{"country":false,"firstname":true,"address2":false,"city":false,"address1":false,"ccnum":true,"ccexpmon":true,"ccvv":true,"lastname":false,"zipcode":false,"phone":true,"additional_charges":false,"ccexpyr":true,"state":false,"productinfo":true,"ccname":true,"email":true,"bankcode":true},"attributeValueMap":{}}}};
/*
export const DATA_NB =  {
    "emi": {
        "id": 14,
        "name": "emi",
        "code": "EMI",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "bank of maharashtra  ": {
        "id": 16,
        "name": "bank of maharashtra  ",
        "code": "BOMB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "development credit bank ": {
        "id": 19,
        "name": "development credit bank ",
        "code": "DCBB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "corporation bank": {
        "id": 18,
        "name": "corporation bank",
        "code": "CRPB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "jammu and kashmir bank": {
        "id": 26,
        "name": "jammu and kashmir bank",
        "code": "JAKB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "cityunion": {
        "id": 38,
        "name": "cityunion",
        "code": "CUBB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "kotak bank": {
        "id": 43,
        "name": "kotak bank",
        "code": "162B",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "state bank of patiala": {
        "id": 40,
        "name": "state bank of patiala",
        "code": "SBPB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "south indian bank": {
        "id": 33,
        "name": "south indian bank",
        "code": "SOIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "indusind bank": {
        "id": 24,
        "name": "indusind bank",
        "code": "INIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "icici bank netbanking": {
        "id": 11,
        "name": "icici bank netbanking",
        "code": "ICIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "cash on delivery": {
        "id": 13,
        "name": "cash on delivery",
        "code": "COD",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "bank of india  ": {
        "id": 15,
        "name": "bank of india  ",
        "code": "BOIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "vijaya bank": {
        "id": 36,
        "name": "vijaya bank",
        "code": "VJYB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "dcb bank - corporate netbanking": {
        "id": 45,
        "name": "dcb bank - corporate netbanking",
        "code": "DCBCORP",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "state bank of bikaner and jaipur": {
        "id": 29,
        "name": "state bank of bikaner and jaipur",
        "code": "SBBJB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "sbi bank netbanking": {
        "id": 12,
        "name": "sbi bank netbanking",
        "code": "SBIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "federal bank ": {
        "id": 20,
        "name": "federal bank ",
        "code": "FEDB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "karur vysya": {
        "id": 28,
        "name": "karur vysya",
        "code": "KRVB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "karnataka bank": {
        "id": 27,
        "name": "karnataka bank",
        "code": "KRKB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "punjab national bank": {
        "id": 46,
        "name": "punjab national bank",
        "code": "PNBB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "dena bank": {
        "id": 21,
        "name": "dena bank",
        "code": "DENN",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "indian overseas bank": {
        "id": 25,
        "name": "indian overseas bank",
        "code": "INOB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "canara bank": {
        "id": 39,
        "name": "canara bank",
        "code": "CABB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "state bank of hyderabad": {
        "id": 30,
        "name": "state bank of hyderabad",
        "code": "SBHB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "yes bank": {
        "id": 37,
        "name": "yes bank",
        "code": "YESB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "catholic syrian bank": {
        "id": 44,
        "name": "catholic syrian bank",
        "code": "CSBN",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "saraswat bank": {
        "id": 47,
        "name": "saraswat bank",
        "code": "SRSWT",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "central bank of india  ": {
        "id": 17,
        "name": "central bank of india  ",
        "code": "CBIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "union bank of india": {
        "id": 34,
        "name": "union bank of india",
        "code": "UBIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "citi bank netbanking": {
        "id": 41,
        "name": "citi bank netbanking",
        "code": "CITNB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "union bank - corporate netbanking": {
        "id": 48,
        "name": "union bank - corporate netbanking",
        "code": "UBIBC",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "indian bank": {
        "id": 23,
        "name": "indian bank",
        "code": "INDB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "state bank of travancore": {
        "id": 32,
        "name": "state bank of travancore",
        "code": "SBTB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "united bank of india": {
        "id": 35,
        "name": "united bank of india",
        "code": "UNIB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "hdfc netbanking": {
        "id": 5,
        "name": "hdfc netbanking",
        "code": "HDFC",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "industrial development bank of india": {
        "id": 22,
        "name": "industrial development bank of india",
        "code": "IDBB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "axis bank netbanking": {
        "id": 3,
        "name": "axis bank netbanking",
        "code": "AXISB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "ing vysya bank": {
        "id": 50,
        "name": "ing vysya bank",
        "code": "INGB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "deutsche bank": {
        "id": 42,
        "name": "deutsche bank",
        "code": "DSHB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "punjab national bank-corporate": {
        "id": 49,
        "name": "punjab national bank-corporate",
        "code": "CPNB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    },
    "state bank of mysore": {
        "id": 31,
        "name": "state bank of mysore",
        "code": "SBMB",
        "enable": true,
        "platformCode": null,
        "mode": "NB",
        "attributeNames": {
            "country": false,
            "firstname": true,
            "address2": false,
            "city": false,
            "address1": false,
            "lastname": false,
            "zipcode": false,
            "phone": true,
            "additional_charges": false,
            "state": false,
            "productinfo": true,
            "email": true,
            "bankcode": true
        },
        "attributeValueMap": {}
    }
};*/
